$axure.loadCurrentPage({
  "url":"个人信息.html",
  "generationDate":new Date(1440052785800.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"daojishi",
"shuzi",
"Login"],
  "page":{
    "packageId":"09563005c52f4b10898575d9fc33b3e3",
    "type":"Axure:Page",
    "name":"个人信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFF2F2F2},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c49d6f87738348e3a882245fc1e1fe34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":159,
              "y":124},
            "size":{
              "width":1560,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78d56cbd56b8442bbc837953e94bac3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":159,
                  "y":124},
                "size":{
                  "width":1560,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户总览/u0.png"}},
{
          "id":"f15ddd515415410ca466921816822bba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":419,
              "y":129},
            "size":{
              "width":163,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"530430cd41134f52b8cdf14cbfb3c121",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":419,
                  "y":129},
                "size":{
                  "width":163,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b237df6e381d425ca97ed0f22b5a8a39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":638,
              "y":170},
            "size":{
              "width":779,
              "height":898},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c31995ba985d481d80230689ff9d0329",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":638,
                  "y":170},
                "size":{
                  "width":779,
                  "height":898},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的积分/u4.png"}},
{
          "id":"c2d739380db04fe99404ccb4b1c0865b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":638,
              "y":222},
            "size":{
              "width":779,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/账户总览/u6_line.png"}},
{
          "id":"87c36ba7cdd648a4b7f93e9c74ac2709",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":665,
              "y":189},
            "size":{
              "width":65,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55a430eaf8d94cf7aa4500b1e1e6dd6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":665,
                  "y":189},
                "size":{
                  "width":65,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"961164d5c22740c3a90536b311ebc9bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":670,
              "y":275},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af2f4e7417db4631a1cb84ef2f7a6441",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":670,
                  "y":275},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62d37ce2c9c84672a1bb0b7aef42f6b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":760,
              "y":275},
            "size":{
              "width":89,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b0dd253a6f64fba9aa6d079874d412f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":760,
                  "y":275},
                "size":{
                  "width":89,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a89af59867574db09745196dd5c2aa95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":670,
              "y":320},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2943ddbef3fc43df810bbe6afb956983",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":670,
                  "y":320},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"279a9bc6649047e9af45977785db6915",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1093,
              "y":321},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26b30af6a3d8428797a140b1c69c7c33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1093,
                  "y":321},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afef315408f341f3a473b589d39308ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":670,
              "y":421},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc8134df753d42e195cbcc0a7b90d614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":670,
                  "y":421},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82ed5ffcc17a4b7f9296ab5cc463c8e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":670,
              "y":470},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f8ed56326014f189000b4bcc3de33d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":670,
                  "y":470},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94856fa601a241a29586dbdc3f67199d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":766,
              "y":470},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de40c2a32c7a45b299e6f5f2c285eab6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":766,
                  "y":470},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"975afaf58f2a406692d4ae9a3612cfd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1093,
              "y":422},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ce147176cde4fad9104253807cddb67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1093,
                  "y":422},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df19faec5fb2400c89cd40ba0007266c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1093,
              "y":473},
            "size":{
              "width":119,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c11d98041ef34e4c9f08c0336add3c91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1093,
                  "y":473},
                "size":{
                  "width":119,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c682b14289ad46cda2b08c09c4015f18",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":300},
            "size":{
              "width":717,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人信息/u27_line.png"}},
{
          "id":"b8e4cf690fef4d05a35c72e029d77ed4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":351},
            "size":{
              "width":717,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人信息/u27_line.png"}},
{
          "id":"41d52f4cf52b42f19606cd2c2bf998c4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":401},
            "size":{
              "width":717,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人信息/u27_line.png"}},
{
          "id":"f0566eb43a8d44deabc5ba2aee4b0781",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":452},
            "size":{
              "width":717,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人信息/u27_line.png"}},
{
          "id":"17346a8b7c9c49aea0a15e7004aad012",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":502},
            "size":{
              "width":717,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/个人信息/u27_line.png"}},
{
          "id":"290226c3d66941abbfe8c9f5591a50e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":760,
              "y":421},
            "size":{
              "width":165,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff59c0cc70384d9a83cf163143239419",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":760,
                  "y":421},
                "size":{
                  "width":165,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5419f55f42234ae3abe6ccc5ac734084",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":670,
              "y":370},
            "size":{
              "width":57,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0deac13ddbaa4c3e8e22c9c2264e3d83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":670,
                  "y":370},
                "size":{
                  "width":57,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00d978a4e8ee417bad84568c958bcc16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1093,
              "y":371},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fdfa59ff67c4816a523edb2d38c260b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1093,
                  "y":371},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8d4123a5bb04375884181e6ca462d11",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":170}},
          "adaptiveStyles":{
},
          "masterId":"976d6fcdccbd4c0ebb7218ce9c6a60b2"},
{
          "id":"e57d7cf6c6c54a62a44df5704232557a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":1099}},
          "adaptiveStyles":{
},
          "masterId":"b57e6da4c0f649ea8c38ffffca6bde22"},
{
          "id":"f89c28cf60f640cdb324bb40848638b5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"30a1e3ad2c17482a9dbf4657c7395ef2"}]}},
  "masters":{
    "976d6fcdccbd4c0ebb7218ce9c6a60b2":{
      "packageId":"976d6fcdccbd4c0ebb7218ce9c6a60b2",
      "type":"Axure:Master",
      "name":"个账中心菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"336c6db3a5f547c1a5c495bdd9d140c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":427,
                "y":180},
              "size":{
                "width":211,
                "height":891},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"77a1a7c7e14d4437a9cd2519711b7643",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":427,
                    "y":180},
                  "size":{
                    "width":211,
                    "height":891},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/账户总览/u67.png"}},
{
            "id":"f7e738347337486581aa5b5b60ebd7ed",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":452,
                "y":212},
              "size":{
                "width":140,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7235ced95cb94b1f95441ede33dd1bb7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":452,
                    "y":212},
                  "size":{
                    "width":140,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2ecc0e915f474d99a94cc79be27c896a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":452,
                "y":455},
              "size":{
                "width":140,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ac83a7d613f74483875fd78ff2aea27c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":452,
                    "y":455},
                  "size":{
                    "width":140,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 积分兑换",
                        "target":{
                          "targetType":"page",
                          "url":"积分兑换.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3e5b05fb3ef34743aa62949f43b763b3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":488,
                "y":415},
              "size":{
                "width":140,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e99d39366274f929fe21460c09a0681",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":488,
                    "y":415},
                  "size":{
                    "width":140,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 获取积分明细",
                        "target":{
                          "targetType":"page",
                          "url":"获取积分明细.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c15a5046e7794906aa8930dac6710b78",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":473,
                "y":275},
              "size":{
                "width":60,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2aa3168b3bd04a908758368b768418a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":473,
                    "y":275},
                  "size":{
                    "width":60,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的积分",
                        "target":{
                          "targetType":"page",
                          "url":"我的积分.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7a7a2ea42ac249a4a152cb14df5ea88d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":473,
                "y":310},
              "size":{
                "width":60,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f78e45a0e19b46a3bc6b834b0e787490",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":473,
                    "y":310},
                  "size":{
                    "width":60,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的现金",
                        "target":{
                          "targetType":"page",
                          "url":"我的现金.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1633860c0fce459dbe332bf90ecd6d06",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":452,
                "y":559},
              "size":{
                "width":140,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"767632f2ac4b4df0a0061b3d64974903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":452,
                    "y":559},
                  "size":{
                    "width":140,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1193020757634e57901cf366575a2ff1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":473,
                "y":597},
              "size":{
                "width":60,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f174dc01a76a4487a7634dbf403178f0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":473,
                    "y":597},
                  "size":{
                    "width":60,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c2bf48ef43db4067852197106bcf28f6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":474,
                "y":630},
              "size":{
                "width":71,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1f135456232a475ea41a57dd395a77d5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":474,
                    "y":630},
                  "size":{
                    "width":71,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 银行卡管理",
                        "target":{
                          "targetType":"page",
                          "url":"银行卡管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"454c48c12c0742a2a669e7d0ecf655f6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":488,
                "y":385},
              "size":{
                "width":140,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9497b7838fda4389accf2f8a93c948eb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":488,
                    "y":385},
                  "size":{
                    "width":140,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 已邀请好友",
                        "target":{
                          "targetType":"page",
                          "url":"已邀请好友.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dbd4ad78ba4341bcb325632dcb399515",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":452,
                "y":504},
              "size":{
                "width":140,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"956225339f274b5c9fedffbcb07a4f45",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":452,
                    "y":504},
                  "size":{
                    "width":140,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 推广明细",
                        "target":{
                          "targetType":"page",
                          "url":"推广明细.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"29841f0d99c44e38aac539df0d4bc8b9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Bold', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"700",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":473,
                "y":245},
              "size":{
                "width":60,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"56837397719640108649de15d3de33ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Bold', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":473,
                    "y":245},
                  "size":{
                    "width":60,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 账户总览",
                        "target":{
                          "targetType":"page",
                          "url":"账户总览.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3206ad2d2c334ce6b3212c8afaf503e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":452,
                "y":349},
              "size":{
                "width":140,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ba7e21cdd0b649f8bb1d49aaa1fea403",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":452,
                    "y":349},
                  "size":{
                    "width":140,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "b57e6da4c0f649ea8c38ffffca6bde22":{
      "packageId":"b57e6da4c0f649ea8c38ffffca6bde22",
      "type":"Axure:Master",
      "name":"foot",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"45784cc34d2243668a240874e0be3625",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "location":{
                "x":-61,
                "y":244},
              "size":{
                "width":1500,
                "height":200}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cb36fade8eda427092d916bd825567ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "location":{
                    "x":-61,
                    "y":244},
                  "size":{
                    "width":1500,
                    "height":200}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页（新）/u81.png"}},
{
            "id":"eb14d540577d4325aef6c8a52dcc111c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":444,
                "y":280},
              "size":{
                "width":394,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f19d5fd6f5d4454f95b2b7e119099e88",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":444,
                    "y":280},
                  "size":{
                    "width":394,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f9cd1eb4f29b428eb0c2df9bdb23fcf0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":545,
                "y":324},
              "size":{
                "width":289,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59bf2f5a09994af893cf0d2cefb2564a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":545,
                    "y":324},
                  "size":{
                    "width":289,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8187b68a46584b3e8e8633bc4d28a79a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":377,
                "y":384},
              "size":{
                "width":623,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2582237d217c46bf878e7852b877a1a6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":377,
                    "y":384},
                  "size":{
                    "width":623,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"869bf3c4952e4e4fa146f90d1b21e694",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":870,
                "y":280},
              "size":{
                "width":73,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9483d61963448a2896b12b59d1e4e5a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":870,
                    "y":280},
                  "size":{
                    "width":73,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 规则协议列表",
                        "target":{
                          "targetType":"page",
                          "url":"规则协议列表.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "30a1e3ad2c17482a9dbf4657c7395ef2":{
      "packageId":"30a1e3ad2c17482a9dbf4657c7395ef2",
      "type":"Axure:Master",
      "name":"首页Tittle",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
        "onLoad":{
          "description":"OnLoad",
          "cases":[{
              "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
              "isNewIfGroup":false,
              "condition":{
                "exprType":"binaryOp",
                "op":"==",
                "leftExpr":{
                  "exprType":"fcall",
                  "functionName":"GetGlobalVariableValue",
                  "arguments":[{
                      "exprType":"globalVariableLiteral",
                      "variableName":"Login"}]},
                "rightExpr":{
                  "exprType":"stringLiteral",
                  "value":"2",
                  "stos":[]}},
              "actions":[{
                  "action":"setFunction",
                  "description":"设置 文字于 标题登录按钮 = &quot;18583632736(积分 1454)&quot;",
                  "expr":{
                    "exprType":"block",
                    "subExprs":[{
                        "exprType":"fcall",
                        "functionName":"SetWidgetRichText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["6e77319d89004f1a88255ae1719600a0"]},
{
                            "exprType":"stringLiteral",
                            "value":"18583632736(积分 1454)",
                            "stos":[]},
{
                            "exprType":"booleanLiteral",
                            "value":true}]}]}}]}]}},
      "diagram":{
        "objects":[{
            "id":"1821ab6eea004513b061fb3aaa34807b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":2000,
                "height":100},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3bfc5bb18d4044fcafe4322f50ed83d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "size":{
                    "width":2000,
                    "height":100},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页（新）/u60.png"}},
{
            "id":"c4e8ce9ccacd42b79e2d44b619262fc6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":260,
                "y":10},
              "size":{
                "width":80,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ff364c73fa734d488d3f95012d9de738",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":260,
                    "y":10},
                  "size":{
                    "width":80,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页（新）/u62.png"}},
{
            "id":"5b9fb65a74544ef1bb7174c29a60cf33",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":340,
                "y":30},
              "size":{
                "width":97,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"89b7bc5ad7e448f6a39423d68a75b281",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":340,
                    "y":30},
                  "size":{
                    "width":97,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5493edf72eac416e8d507c5bf9a3a54a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":500,
                "y":37},
              "size":{
                "width":41,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e04a737dd06a42dbb80844f1e2ce75d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":500,
                    "y":37},
                  "size":{
                    "width":41,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（新）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（新）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7020ea293ef94676b8b39c2cc702250a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":581,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24629670b3e34032a452acd4dfe4ecb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":581,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 账户总览",
                        "target":{
                          "targetType":"page",
                          "url":"账户总览.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"95d40ea0e0d04411a1f93c924484046c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":840,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9d067be757bc4d9eb55a68f2214e3ab6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":840,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"case1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 帮助中心",
                        "target":{
                          "targetType":"page",
                          "url":"帮助中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cce804af75f845aaaef9cf4ea298aa28",
            "label":"标题登录按钮",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":970,
                "y":37},
              "size":{
                "width":245,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e77319d89004f1a88255ae1719600a0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":970,
                    "y":37},
                  "size":{
                    "width":245,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"2",
                        "stos":[]}},
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]},
{
                    "description":"Case 2<br> (Else If 值于 Login == &quot;1&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}},
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"2",
                        "stos":[]}},
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"显示 退出登录按钮",
                        "objectsToFades":[{
                            "objectPath":["117de39a6b174043ab639e4de8e4f32b"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f8ae19a9cdd744518715d4848eb273d4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":702,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7bd1fee1ab164844b5cb5814b7d21eb0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":702,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 积分商城（caili）",
                        "target":{
                          "targetType":"page",
                          "url":"积分商城（caili）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"117de39a6b174043ab639e4de8e4f32b",
            "label":"退出登录按钮",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":968,
                "y":74},
              "size":{
                "width":70,
                "height":70},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 值于 Login = &quot;1&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"Login"},
{
                                  "exprType":"stringLiteral",
                                  "value":"1",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（新）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（新）.html",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"fadeWidget",
                        "description":"隐藏 This",
                        "objectsToFades":[{
                            "objectPath":["117de39a6b174043ab639e4de8e4f32b"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"094f13922d86494393e52aeae360066d",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"34968a8b32ae4822b5b6e14742aa4f37",
                    "label":"",
                    "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"67d700fd08904918b4738f1d0e6d4d71",
                        "label":"",
                        "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"5465cbdd1fca49f3927ee512d77e43bc",
                            "label":"",
                            "isContained":true,
                            "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'微软雅黑 Regular', '微软雅黑'",
                              "fontWeight":"400",
                              "fontStyle":"normal",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "size":{
                                "width":70,
                                "height":40}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/首页（新）/u78.png"}}]}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}}},
  "objectPaths":{
    "c49d6f87738348e3a882245fc1e1fe34":{
      "scriptId":"u0"},
    "78d56cbd56b8442bbc837953e94bac3d":{
      "scriptId":"u1"},
    "f15ddd515415410ca466921816822bba":{
      "scriptId":"u2"},
    "530430cd41134f52b8cdf14cbfb3c121":{
      "scriptId":"u3"},
    "b237df6e381d425ca97ed0f22b5a8a39":{
      "scriptId":"u4"},
    "c31995ba985d481d80230689ff9d0329":{
      "scriptId":"u5"},
    "c2d739380db04fe99404ccb4b1c0865b":{
      "scriptId":"u6"},
    "87c36ba7cdd648a4b7f93e9c74ac2709":{
      "scriptId":"u7"},
    "55a430eaf8d94cf7aa4500b1e1e6dd6f":{
      "scriptId":"u8"},
    "961164d5c22740c3a90536b311ebc9bd":{
      "scriptId":"u9"},
    "af2f4e7417db4631a1cb84ef2f7a6441":{
      "scriptId":"u10"},
    "62d37ce2c9c84672a1bb0b7aef42f6b5":{
      "scriptId":"u11"},
    "0b0dd253a6f64fba9aa6d079874d412f":{
      "scriptId":"u12"},
    "a89af59867574db09745196dd5c2aa95":{
      "scriptId":"u13"},
    "2943ddbef3fc43df810bbe6afb956983":{
      "scriptId":"u14"},
    "279a9bc6649047e9af45977785db6915":{
      "scriptId":"u15"},
    "26b30af6a3d8428797a140b1c69c7c33":{
      "scriptId":"u16"},
    "afef315408f341f3a473b589d39308ef":{
      "scriptId":"u17"},
    "dc8134df753d42e195cbcc0a7b90d614":{
      "scriptId":"u18"},
    "82ed5ffcc17a4b7f9296ab5cc463c8e1":{
      "scriptId":"u19"},
    "1f8ed56326014f189000b4bcc3de33d6":{
      "scriptId":"u20"},
    "94856fa601a241a29586dbdc3f67199d":{
      "scriptId":"u21"},
    "de40c2a32c7a45b299e6f5f2c285eab6":{
      "scriptId":"u22"},
    "975afaf58f2a406692d4ae9a3612cfd5":{
      "scriptId":"u23"},
    "1ce147176cde4fad9104253807cddb67":{
      "scriptId":"u24"},
    "df19faec5fb2400c89cd40ba0007266c":{
      "scriptId":"u25"},
    "c11d98041ef34e4c9f08c0336add3c91":{
      "scriptId":"u26"},
    "c682b14289ad46cda2b08c09c4015f18":{
      "scriptId":"u27"},
    "b8e4cf690fef4d05a35c72e029d77ed4":{
      "scriptId":"u28"},
    "41d52f4cf52b42f19606cd2c2bf998c4":{
      "scriptId":"u29"},
    "f0566eb43a8d44deabc5ba2aee4b0781":{
      "scriptId":"u30"},
    "17346a8b7c9c49aea0a15e7004aad012":{
      "scriptId":"u31"},
    "290226c3d66941abbfe8c9f5591a50e3":{
      "scriptId":"u32"},
    "ff59c0cc70384d9a83cf163143239419":{
      "scriptId":"u33"},
    "5419f55f42234ae3abe6ccc5ac734084":{
      "scriptId":"u34"},
    "0deac13ddbaa4c3e8e22c9c2264e3d83":{
      "scriptId":"u35"},
    "00d978a4e8ee417bad84568c958bcc16":{
      "scriptId":"u36"},
    "6fdfa59ff67c4816a523edb2d38c260b":{
      "scriptId":"u37"},
    "f8d4123a5bb04375884181e6ca462d11":{
      "scriptId":"u38",
      "336c6db3a5f547c1a5c495bdd9d140c2":{
        "scriptId":"u39"},
      "77a1a7c7e14d4437a9cd2519711b7643":{
        "scriptId":"u40"},
      "f7e738347337486581aa5b5b60ebd7ed":{
        "scriptId":"u41"},
      "7235ced95cb94b1f95441ede33dd1bb7":{
        "scriptId":"u42"},
      "2ecc0e915f474d99a94cc79be27c896a":{
        "scriptId":"u43"},
      "ac83a7d613f74483875fd78ff2aea27c":{
        "scriptId":"u44"},
      "3e5b05fb3ef34743aa62949f43b763b3":{
        "scriptId":"u45"},
      "6e99d39366274f929fe21460c09a0681":{
        "scriptId":"u46"},
      "c15a5046e7794906aa8930dac6710b78":{
        "scriptId":"u47"},
      "2aa3168b3bd04a908758368b768418a8":{
        "scriptId":"u48"},
      "7a7a2ea42ac249a4a152cb14df5ea88d":{
        "scriptId":"u49"},
      "f78e45a0e19b46a3bc6b834b0e787490":{
        "scriptId":"u50"},
      "1633860c0fce459dbe332bf90ecd6d06":{
        "scriptId":"u51"},
      "767632f2ac4b4df0a0061b3d64974903":{
        "scriptId":"u52"},
      "1193020757634e57901cf366575a2ff1":{
        "scriptId":"u53"},
      "f174dc01a76a4487a7634dbf403178f0":{
        "scriptId":"u54"},
      "c2bf48ef43db4067852197106bcf28f6":{
        "scriptId":"u55"},
      "1f135456232a475ea41a57dd395a77d5":{
        "scriptId":"u56"},
      "454c48c12c0742a2a669e7d0ecf655f6":{
        "scriptId":"u57"},
      "9497b7838fda4389accf2f8a93c948eb":{
        "scriptId":"u58"},
      "dbd4ad78ba4341bcb325632dcb399515":{
        "scriptId":"u59"},
      "956225339f274b5c9fedffbcb07a4f45":{
        "scriptId":"u60"},
      "29841f0d99c44e38aac539df0d4bc8b9":{
        "scriptId":"u61"},
      "56837397719640108649de15d3de33ca":{
        "scriptId":"u62"},
      "3206ad2d2c334ce6b3212c8afaf503e2":{
        "scriptId":"u63"},
      "ba7e21cdd0b649f8bb1d49aaa1fea403":{
        "scriptId":"u64"}},
    "e57d7cf6c6c54a62a44df5704232557a":{
      "scriptId":"u65",
      "45784cc34d2243668a240874e0be3625":{
        "scriptId":"u66"},
      "cb36fade8eda427092d916bd825567ca":{
        "scriptId":"u67"},
      "eb14d540577d4325aef6c8a52dcc111c":{
        "scriptId":"u68"},
      "f19d5fd6f5d4454f95b2b7e119099e88":{
        "scriptId":"u69"},
      "f9cd1eb4f29b428eb0c2df9bdb23fcf0":{
        "scriptId":"u70"},
      "59bf2f5a09994af893cf0d2cefb2564a":{
        "scriptId":"u71"},
      "8187b68a46584b3e8e8633bc4d28a79a":{
        "scriptId":"u72"},
      "2582237d217c46bf878e7852b877a1a6":{
        "scriptId":"u73"},
      "869bf3c4952e4e4fa146f90d1b21e694":{
        "scriptId":"u74"},
      "b9483d61963448a2896b12b59d1e4e5a":{
        "scriptId":"u75"}},
    "f89c28cf60f640cdb324bb40848638b5":{
      "scriptId":"u76",
      "1821ab6eea004513b061fb3aaa34807b":{
        "scriptId":"u77"},
      "3bfc5bb18d4044fcafe4322f50ed83d9":{
        "scriptId":"u78"},
      "c4e8ce9ccacd42b79e2d44b619262fc6":{
        "scriptId":"u79"},
      "ff364c73fa734d488d3f95012d9de738":{
        "scriptId":"u80"},
      "5b9fb65a74544ef1bb7174c29a60cf33":{
        "scriptId":"u81"},
      "89b7bc5ad7e448f6a39423d68a75b281":{
        "scriptId":"u82"},
      "5493edf72eac416e8d507c5bf9a3a54a":{
        "scriptId":"u83"},
      "e04a737dd06a42dbb80844f1e2ce75d3":{
        "scriptId":"u84"},
      "7020ea293ef94676b8b39c2cc702250a":{
        "scriptId":"u85"},
      "24629670b3e34032a452acd4dfe4ecb1":{
        "scriptId":"u86"},
      "95d40ea0e0d04411a1f93c924484046c":{
        "scriptId":"u87"},
      "9d067be757bc4d9eb55a68f2214e3ab6":{
        "scriptId":"u88"},
      "cce804af75f845aaaef9cf4ea298aa28":{
        "scriptId":"u89"},
      "6e77319d89004f1a88255ae1719600a0":{
        "scriptId":"u90"},
      "f8ae19a9cdd744518715d4848eb273d4":{
        "scriptId":"u91"},
      "7bd1fee1ab164844b5cb5814b7d21eb0":{
        "scriptId":"u92"},
      "117de39a6b174043ab639e4de8e4f32b":{
        "scriptId":"u93"},
      "34968a8b32ae4822b5b6e14742aa4f37":{
        "scriptId":"u94"},
      "67d700fd08904918b4738f1d0e6d4d71":{
        "scriptId":"u95"},
      "5465cbdd1fca49f3927ee512d77e43bc":{
        "scriptId":"u96"}}}});