$axure.loadCurrentPage({
  "url":"后台使用流程.html",
  "generationDate":new Date(1441088580401.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"daojishi",
"shuzi",
"Login"],
  "page":{
    "packageId":"e4502efd909a4d71b8b8ff50de81b54b",
    "type":"Axure:Page",
    "name":"后台使用流程",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cb460064ab2c41e68294f64e494ebf2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1c21c10ea6e4e0ebf062a52a2330252",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd38f2a736164a2c9e30f628b8e1ef6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":10,
              "y":66},
            "size":{
              "width":1790,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53a63d652f2f4520af51a151eec5c824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":10,
                  "y":66},
                "size":{
                  "width":1790,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台使用流程/u2.png"}},
{
          "id":"3bbfc74e4b854994b36c5e186287604d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":40,
              "y":234},
            "size":{
              "width":70,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"124dd255aee642aa9f8197d7dc2728ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":40,
                  "y":234},
                "size":{
                  "width":70,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台使用流程/u4.png"}},
{
          "id":"8a4eb9eeb8474ab6952da7ef30b055e3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":170,
              "y":226},
            "size":{
              "width":110,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35108d6fa70f4353b056e034f6ecab0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":170,
                  "y":226},
                "size":{
                  "width":110,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台使用流程/u6.png"}},
{
          "id":"bf27a49d19cb4bb286f0bea28a7da2b0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":340,
              "y":226},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96876b3cb7534dab886168d5d72c1c4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":340,
                  "y":226},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面结构图/u2.png"}},
{
          "id":"a6c8093ba0f946438de8922fe2c04af0",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":530,
              "y":226},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7f32e8f3ebe4ae18d4d1dcbb242074d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":530,
                  "y":226},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户使用流程图/u16.png"}},
{
          "id":"4bc9927ccc35407d9caeb75e2b6e5cec",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":830,
              "y":226},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f6f518a520a411b9e76acada02523fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":830,
                  "y":226},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面结构图/u2.png"}},
{
          "id":"38c437bddb3d4a659429adf9b5b4b624",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":530,
              "y":346},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b85107117faa4a39b2f3e017ab36adbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":530,
                  "y":346},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面结构图/u2.png"}},
{
          "id":"c9cc0d4825554dd095b601225425105c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":830,
              "y":346},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b31fcde243b4c4a89b62f61e2cd2de6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":830,
                  "y":346},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户使用流程图/u16.png"}},
{
          "id":"0ebedc96e5f84cd882e110f6d13428e0",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":110,
              "y":256}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1d622f9f75457abfa7d6d1dc687a87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":110,
                  "y":256}},
              "adaptiveStyles":{
}}]},
{
          "id":"e6a2a4e31ec140d29977b30150b8fb8e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":280,
              "y":256}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba186ccb12a4438dbecc12131d4b77cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":280,
                  "y":256}},
              "adaptiveStyles":{
}}]},
{
          "id":"5c8bb033fec54cb1886e6ca2c3ed51cd",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":440,
              "y":256}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"288aa69a129c42429154764f9f921ce8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":440,
                  "y":256}},
              "adaptiveStyles":{
}}]},
{
          "id":"fb0d69a8b9364a0697282a6f6ea39200",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":630,
              "y":256}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4686784a0c6241e3b33ff3fd51fa9f83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":630,
                  "y":256}},
              "adaptiveStyles":{
}}]},
{
          "id":"faef950e7be949bfbe2b86d350a3fe8e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":580,
              "y":286}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fc8e637e3c643c2acc1ab2d4bd81872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":580,
                  "y":286}},
              "adaptiveStyles":{
}}]},
{
          "id":"4873c4dac2af44cb9e0ad37bbce8bb4e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":880,
              "y":346}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60c5a7f146494456b3cc461046c1e32c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":880,
                  "y":346}},
              "adaptiveStyles":{
}}]},
{
          "id":"f2488f13c1a5481fbb9a89cdf7cf2099",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":674,
              "y":352},
            "size":{
              "width":110,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e5b8987fe35435b9dab8fd4cc3df919",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":674,
                  "y":352},
                "size":{
                  "width":110,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台使用流程/u30.png"}},
{
          "id":"14a09634dded48beaf51a508bcfa07fd",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":784,
              "y":377}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3100bca5109e4d9baafee795a584eb2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":784,
                  "y":377}},
              "adaptiveStyles":{
}}]},
{
          "id":"e179c6da91af49cba2b0d3a386e4b365",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":630,
              "y":376}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74f766e9e8f844c0a2722bf83cf99ae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":630,
                  "y":376}},
              "adaptiveStyles":{
}}]},
{
          "id":"ee9804ddd118471ea49c62e1f374e9f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":10,
              "y":486},
            "size":{
              "width":193,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e59c28d8bb0d49a68572fb9183a91da6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":10,
                  "y":486},
                "size":{
                  "width":193,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03bec4cf943c42e2960e21fdbb57d6eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":10,
              "y":534},
            "size":{
              "width":1790,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bee30854a3b64feab665455bd0040e52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":10,
                  "y":534},
                "size":{
                  "width":1790,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台使用流程/u2.png"}},
{
          "id":"065b810f3d3e41818e335aa69c042815",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":20,
              "y":676},
            "size":{
              "width":80,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d2758e1743c4e8da4c64dd4f33de5f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":20,
                  "y":676},
                "size":{
                  "width":80,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台使用流程/u40.png"}},
{
          "id":"54aded4c914f42b6a9790ba6f9ca7450",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":150,
              "y":676},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f2196fbabce405baae099dfc061d728",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":150,
                  "y":676},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面结构图/u2.png"}},
{
          "id":"aa5623508651432ba4686015ecec3342",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":310,
              "y":672},
            "size":{
              "width":140,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d389a3f041a943089693f7fc294e2793",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":310,
                  "y":672},
                "size":{
                  "width":140,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台使用流程/u44.png"}},
{
          "id":"8d14f982935c4cfab25d037cd5a9e526",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":520,
              "y":674},
            "size":{
              "width":140,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11dfbd4b82434674aa1841bfe7114160",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":520,
                  "y":674},
                "size":{
                  "width":140,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台使用流程/u46.png"}},
{
          "id":"a31f2d29a14246ba9311002e45ec7bdd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":740,
              "y":676},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c59a2aa38ca48a19ef9db2340c20637",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":740,
                  "y":676},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户使用流程图/u16.png"}},
{
          "id":"e340e7f8f70e43a6933fedae8aad4b49",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":910,
              "y":676},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd60a7f0beeb40f2a49dceed0ee254c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":910,
                  "y":676},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面结构图/u2.png"}},
{
          "id":"1fad1f7f048247eab0ace71244cf9fe3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":330,
              "y":786},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67965c31d0224b90b9ab6c45a4e8b732",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":330,
                  "y":786},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面结构图/u2.png"}},
{
          "id":"cbafc3e28a8b43039dcaf7224b68d8eb",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":100,
              "y":706}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28fe5802104241b2a18d98403ab57445",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":100,
                  "y":706}},
              "adaptiveStyles":{
}}]},
{
          "id":"176e6ea38f0d4966b68947a6ea85dbbd",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":250,
              "y":706}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e820e57cf14acfb04f6b26d7afba0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":250,
                  "y":706}},
              "adaptiveStyles":{
}}]},
{
          "id":"2b56f3c2fe744f9e83e54d41658ef9e6",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":450,
              "y":707}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d70912099523439bb8e26721d53a95ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":450,
                  "y":707}},
              "adaptiveStyles":{
}}]},
{
          "id":"efb3ff0b8965489a86e48e91f80efeef",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":330,
              "y":566},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4823722c41b496ca80730479eaaea41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":330,
                  "y":566},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/页面结构图/u2.png"}},
{
          "id":"90e0f917606047f1b09e22289544e70c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":380,
              "y":672}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4950221444f490998efabff9a0f4171",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":380,
                  "y":672}},
              "adaptiveStyles":{
}}]},
{
          "id":"b21676b6d8c547cb8716c9b65e156153",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":960,
              "y":736}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ea84268d54745a1b5ac4a07079e305a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":960,
                  "y":736}},
              "adaptiveStyles":{
}}]},
{
          "id":"a788e2c94a894adbb4362e5283b3a450",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":380,
              "y":786}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7850f417913a418b853468074029acd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":380,
                  "y":786}},
              "adaptiveStyles":{
}}]},
{
          "id":"29c1f335e5574cd9b616bf35f0337585",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":660,
              "y":706}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73e62b3c895c4fa0b9c46de3c1d5e55f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":660,
                  "y":706}},
              "adaptiveStyles":{
}}]},
{
          "id":"2ef32a57a1984850b441545156dcb827",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":840,
              "y":706}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22d7a35bc4f1422cb7dac08798afd4be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":840,
                  "y":706}},
              "adaptiveStyles":{
}}]},
{
          "id":"491474e5b5904ffa9ef8e7c6bed69574",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":540,
              "y":604},
            "size":{
              "width":100,
              "height":60},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e239677152a040dcae25c4d2eb3927a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":540,
                  "y":604},
                "size":{
                  "width":100,
                  "height":60},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台使用流程/u72.png"}},
{
          "id":"54e2f5aff8a8481e8a63ed272faf0e8d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":910,
              "y":606},
            "size":{
              "width":100,
              "height":60},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0b305810c564efe97cfacfc33101ecf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":910,
                  "y":606},
                "size":{
                  "width":100,
                  "height":60},
                "borderWidth":"3"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/后台使用流程/u72.png"}},
{
          "id":"71d5da9114ce4377872ed434b0adbdb2",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":880,
              "y":406}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3506389356c4ee09c90dbc61c5caf9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":880,
                  "y":406}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "cb460064ab2c41e68294f64e494ebf2c":{
      "scriptId":"u0"},
    "a1c21c10ea6e4e0ebf062a52a2330252":{
      "scriptId":"u1"},
    "bd38f2a736164a2c9e30f628b8e1ef6a":{
      "scriptId":"u2"},
    "53a63d652f2f4520af51a151eec5c824":{
      "scriptId":"u3"},
    "3bbfc74e4b854994b36c5e186287604d":{
      "scriptId":"u4"},
    "124dd255aee642aa9f8197d7dc2728ea":{
      "scriptId":"u5"},
    "8a4eb9eeb8474ab6952da7ef30b055e3":{
      "scriptId":"u6"},
    "35108d6fa70f4353b056e034f6ecab0a":{
      "scriptId":"u7"},
    "bf27a49d19cb4bb286f0bea28a7da2b0":{
      "scriptId":"u8"},
    "96876b3cb7534dab886168d5d72c1c4f":{
      "scriptId":"u9"},
    "a6c8093ba0f946438de8922fe2c04af0":{
      "scriptId":"u10"},
    "a7f32e8f3ebe4ae18d4d1dcbb242074d":{
      "scriptId":"u11"},
    "4bc9927ccc35407d9caeb75e2b6e5cec":{
      "scriptId":"u12"},
    "2f6f518a520a411b9e76acada02523fa":{
      "scriptId":"u13"},
    "38c437bddb3d4a659429adf9b5b4b624":{
      "scriptId":"u14"},
    "b85107117faa4a39b2f3e017ab36adbc":{
      "scriptId":"u15"},
    "c9cc0d4825554dd095b601225425105c":{
      "scriptId":"u16"},
    "6b31fcde243b4c4a89b62f61e2cd2de6":{
      "scriptId":"u17"},
    "0ebedc96e5f84cd882e110f6d13428e0":{
      "scriptId":"u18"},
    "5f1d622f9f75457abfa7d6d1dc687a87":{
      "scriptId":"u19"},
    "e6a2a4e31ec140d29977b30150b8fb8e":{
      "scriptId":"u20"},
    "ba186ccb12a4438dbecc12131d4b77cc":{
      "scriptId":"u21"},
    "5c8bb033fec54cb1886e6ca2c3ed51cd":{
      "scriptId":"u22"},
    "288aa69a129c42429154764f9f921ce8":{
      "scriptId":"u23"},
    "fb0d69a8b9364a0697282a6f6ea39200":{
      "scriptId":"u24"},
    "4686784a0c6241e3b33ff3fd51fa9f83":{
      "scriptId":"u25"},
    "faef950e7be949bfbe2b86d350a3fe8e":{
      "scriptId":"u26"},
    "3fc8e637e3c643c2acc1ab2d4bd81872":{
      "scriptId":"u27"},
    "4873c4dac2af44cb9e0ad37bbce8bb4e":{
      "scriptId":"u28"},
    "60c5a7f146494456b3cc461046c1e32c":{
      "scriptId":"u29"},
    "f2488f13c1a5481fbb9a89cdf7cf2099":{
      "scriptId":"u30"},
    "0e5b8987fe35435b9dab8fd4cc3df919":{
      "scriptId":"u31"},
    "14a09634dded48beaf51a508bcfa07fd":{
      "scriptId":"u32"},
    "3100bca5109e4d9baafee795a584eb2e":{
      "scriptId":"u33"},
    "e179c6da91af49cba2b0d3a386e4b365":{
      "scriptId":"u34"},
    "74f766e9e8f844c0a2722bf83cf99ae1":{
      "scriptId":"u35"},
    "ee9804ddd118471ea49c62e1f374e9f7":{
      "scriptId":"u36"},
    "e59c28d8bb0d49a68572fb9183a91da6":{
      "scriptId":"u37"},
    "03bec4cf943c42e2960e21fdbb57d6eb":{
      "scriptId":"u38"},
    "bee30854a3b64feab665455bd0040e52":{
      "scriptId":"u39"},
    "065b810f3d3e41818e335aa69c042815":{
      "scriptId":"u40"},
    "1d2758e1743c4e8da4c64dd4f33de5f8":{
      "scriptId":"u41"},
    "54aded4c914f42b6a9790ba6f9ca7450":{
      "scriptId":"u42"},
    "8f2196fbabce405baae099dfc061d728":{
      "scriptId":"u43"},
    "aa5623508651432ba4686015ecec3342":{
      "scriptId":"u44"},
    "d389a3f041a943089693f7fc294e2793":{
      "scriptId":"u45"},
    "8d14f982935c4cfab25d037cd5a9e526":{
      "scriptId":"u46"},
    "11dfbd4b82434674aa1841bfe7114160":{
      "scriptId":"u47"},
    "a31f2d29a14246ba9311002e45ec7bdd":{
      "scriptId":"u48"},
    "0c59a2aa38ca48a19ef9db2340c20637":{
      "scriptId":"u49"},
    "e340e7f8f70e43a6933fedae8aad4b49":{
      "scriptId":"u50"},
    "bd60a7f0beeb40f2a49dceed0ee254c5":{
      "scriptId":"u51"},
    "1fad1f7f048247eab0ace71244cf9fe3":{
      "scriptId":"u52"},
    "67965c31d0224b90b9ab6c45a4e8b732":{
      "scriptId":"u53"},
    "cbafc3e28a8b43039dcaf7224b68d8eb":{
      "scriptId":"u54"},
    "28fe5802104241b2a18d98403ab57445":{
      "scriptId":"u55"},
    "176e6ea38f0d4966b68947a6ea85dbbd":{
      "scriptId":"u56"},
    "67e820e57cf14acfb04f6b26d7afba0d":{
      "scriptId":"u57"},
    "2b56f3c2fe744f9e83e54d41658ef9e6":{
      "scriptId":"u58"},
    "d70912099523439bb8e26721d53a95ad":{
      "scriptId":"u59"},
    "efb3ff0b8965489a86e48e91f80efeef":{
      "scriptId":"u60"},
    "b4823722c41b496ca80730479eaaea41":{
      "scriptId":"u61"},
    "90e0f917606047f1b09e22289544e70c":{
      "scriptId":"u62"},
    "b4950221444f490998efabff9a0f4171":{
      "scriptId":"u63"},
    "b21676b6d8c547cb8716c9b65e156153":{
      "scriptId":"u64"},
    "7ea84268d54745a1b5ac4a07079e305a":{
      "scriptId":"u65"},
    "a788e2c94a894adbb4362e5283b3a450":{
      "scriptId":"u66"},
    "7850f417913a418b853468074029acd2":{
      "scriptId":"u67"},
    "29c1f335e5574cd9b616bf35f0337585":{
      "scriptId":"u68"},
    "73e62b3c895c4fa0b9c46de3c1d5e55f":{
      "scriptId":"u69"},
    "2ef32a57a1984850b441545156dcb827":{
      "scriptId":"u70"},
    "22d7a35bc4f1422cb7dac08798afd4be":{
      "scriptId":"u71"},
    "491474e5b5904ffa9ef8e7c6bed69574":{
      "scriptId":"u72"},
    "e239677152a040dcae25c4d2eb3927a3":{
      "scriptId":"u73"},
    "54e2f5aff8a8481e8a63ed272faf0e8d":{
      "scriptId":"u74"},
    "c0b305810c564efe97cfacfc33101ecf":{
      "scriptId":"u75"},
    "71d5da9114ce4377872ed434b0adbdb2":{
      "scriptId":"u76"},
    "c3506389356c4ee09c90dbc61c5caf9d":{
      "scriptId":"u77"}}});