$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1441088581259.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"daojishi",
"shuzi",
"Login"],
  "page":{
    "packageId":"84196ad062b2437884fade3d1190923d",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9cea0dc7b38c4ccc957a577b80edcc9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":262,
              "y":170},
            "size":{
              "width":1000,
              "height":665},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e44fb9f04ea841d2bccc7a1f6beac8c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":262,
                  "y":170},
                "size":{
                  "width":1000,
                  "height":665},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u0.png"}},
{
          "id":"b6c8afd032bb49639d55f70f336a49ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":1500,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94458dbd0baf4d4bba571d1920791261",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":1500,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u14.png"}},
{
          "id":"b8ec6d74f33d4292af5c4541dc88640d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":489,
              "y":232},
            "size":{
              "width":97,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76251edecdfa42fc9fb37fcedab389bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":489,
                  "y":232},
                "size":{
                  "width":97,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37da911f369249bf812dc928eb3d1d3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":358,
              "y":358},
            "size":{
              "width":29,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b976c0e24d346c5a157e8695b63c0b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":358},
                "size":{
                  "width":29,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cbc708b0c4fe4892bfaec56712d3275c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "opacity":"0.8",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":433,
              "y":577},
            "size":{
              "width":247,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be36a887982443ab160fdeccb0ed00c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "opacity":"0.8",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":433,
                  "y":577},
                "size":{
                  "width":247,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/注册/u8.png"}},
{
          "id":"9f6db67f99734f88a3fa82d5f58a5b9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":549,
              "y":622},
            "size":{
              "width":147,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff03a182722c4c89b616a0c306f09e32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":549,
                  "y":622},
                "size":{
                  "width":147,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"48db2ae47e104e48b69d25d3a2b61adc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":358,
              "y":431},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29bf3f2b1fe04581b39c43f5c133f84c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":431},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e952bc1aecff462b969144841e1b28d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":550,
              "y":411},
            "size":{
              "width":149,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a36ac84088948d4bb4522411f31219f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":550,
                  "y":411},
                "size":{
                  "width":149,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u14.png"}},
{
          "id":"366052cf94dc4d1bb4f144e34169591e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":330,
              "y":485},
            "size":{
              "width":71,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"466936ff82664baf9f1009390e9c3be3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":330,
                  "y":485},
                "size":{
                  "width":71,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb4223973be147e58ba75d8978e1b777",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":358,
              "y":302},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7914748997724bbba3a15d14cb5c8117",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":358,
                  "y":302},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c361a22f1af46678640f7169ba9268e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF01B0F1,
              "opacity":1},
            "location":{
              "x":553,
              "y":528},
            "size":{
              "width":73,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a5fa38960794c09a0f5db7b48efaa0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF01B0F1,
                  "opacity":1},
                "location":{
                  "x":553,
                  "y":528},
                "size":{
                  "width":73,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 相关协议页面",
                      "target":{
                        "targetType":"page",
                        "url":"相关协议页面.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"939de69799b441dc8569cbff4ad0342b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"12px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF01B0F1,
              "opacity":1},
            "location":{
              "x":617,
              "y":528},
            "size":{
              "width":73,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9369bb11b7b44e2904f4b23e00802fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"12px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF01B0F1,
                  "opacity":1},
                "location":{
                  "x":617,
                  "y":528},
                "size":{
                  "width":73,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 相关协议页面",
                      "target":{
                        "targetType":"page",
                        "url":"相关协议页面.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62d8b1a60f3846528bbb8f923aff0766",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":438,
              "y":528},
            "size":{
              "width":117,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06dbf868b64c4867bc1337bd33bcff7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":438,
                  "y":528},
                "size":{
                  "width":117,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c47f415487c14e888643aeeaa6aea655",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":260,
              "y":135},
            "size":{
              "width":163,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7e236feebc34cbe86c67bd311679431",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":135},
                "size":{
                  "width":163,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b5280cf1d9d4f99bf5f7d8bd4c064fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":438,
              "y":294},
            "size":{
              "width":242,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86c7dbbb2acd4e5fadf3ee7c887ebc1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":438,
                  "y":294},
                "size":{
                  "width":242,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u28.png"}},
{
          "id":"34acab0d4e2b41a58f54dc46ae494391",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":438,
              "y":350},
            "size":{
              "width":242,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"538fa9b152d14b80b3c875332f6c167d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":438,
                  "y":350},
                "size":{
                  "width":242,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u28.png"}},
{
          "id":"1d515e62b3674826b1273fa5acf7b398",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":438,
              "y":420},
            "size":{
              "width":112,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddc962957efd4f6ea49f21679c4111f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":438,
                  "y":420},
                "size":{
                  "width":112,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u32.png"}},
{
          "id":"b934ecfb31cc4b1a9d9f080213016dc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":438,
              "y":477},
            "size":{
              "width":112,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fe8ebbd3dc743f09dc92b8e984023e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":438,
                  "y":477},
                "size":{
                  "width":112,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u32.png"}},
{
          "id":"849b8bf109804d32bef9cd41103d6fb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":560,
              "y":477},
            "size":{
              "width":126,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"188c659962a84b438785c5ccacf05cda",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":560,
                  "y":477},
                "size":{
                  "width":126,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u36.png"}},
{
          "id":"2b5f00055c874a0aac769fce3afaeec2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"13px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC3300,
              "opacity":1},
            "location":{
              "x":690,
              "y":303},
            "size":{
              "width":79,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85747caef489432ba3578300ddc17582",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"13px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC3300,
                  "opacity":1},
                "location":{
                  "x":690,
                  "y":303},
                "size":{
                  "width":79,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"580a72cab52f4321b63e56031346a833",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":832,
              "y":232},
            "size":{
              "width":10,
              "height":399},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/注册/u40_line.png"}},
{
          "id":"8b52a103c5d247e6968f5516d9f31ef3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":892,
              "y":232},
            "size":{
              "width":319,
              "height":331},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c9066ae4a774684b452d1cd92062ecf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":892,
                  "y":232},
                "size":{
                  "width":319,
                  "height":331},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u23.png"}},
{
          "id":"d153bc5a85a94bababfc07002bfdd8b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":696,
              "y":477},
            "size":{
              "width":126,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d06950dd5b44f24b9c2f9654b735f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":696,
                  "y":477},
                "size":{
                  "width":126,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u36.png"}},
{
          "id":"0cc79d779b8043989cefcc40cae263df",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"30a1e3ad2c17482a9dbf4657c7395ef2"},
{
          "id":"c8b61cd01370453a837ff9c03c579fb1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":845}},
          "adaptiveStyles":{
},
          "masterId":"b57e6da4c0f649ea8c38ffffca6bde22"},
{
          "id":"e3ebc0580f404b5aab930055669c2fc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":644,
              "y":354},
            "size":{
              "width":33,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e73e111a4284a0b87fe711be6f22c60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":644,
                  "y":354},
                "size":{
                  "width":33,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u77.png"}}]}},
  "masters":{
    "30a1e3ad2c17482a9dbf4657c7395ef2":{
      "packageId":"30a1e3ad2c17482a9dbf4657c7395ef2",
      "type":"Axure:Master",
      "name":"首页Tittle",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
        "onLoad":{
          "description":"OnLoad",
          "cases":[{
              "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
              "isNewIfGroup":false,
              "condition":{
                "exprType":"binaryOp",
                "op":"==",
                "leftExpr":{
                  "exprType":"fcall",
                  "functionName":"GetGlobalVariableValue",
                  "arguments":[{
                      "exprType":"globalVariableLiteral",
                      "variableName":"Login"}]},
                "rightExpr":{
                  "exprType":"stringLiteral",
                  "value":"2",
                  "stos":[]}},
              "actions":[{
                  "action":"setFunction",
                  "description":"设置 文字于 标题登录按钮 = &quot;18583632736(积分 1454)&quot;",
                  "expr":{
                    "exprType":"block",
                    "subExprs":[{
                        "exprType":"fcall",
                        "functionName":"SetWidgetRichText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["6e77319d89004f1a88255ae1719600a0"]},
{
                            "exprType":"stringLiteral",
                            "value":"18583632736(积分 1454)",
                            "stos":[]},
{
                            "exprType":"booleanLiteral",
                            "value":true}]}]}}]}]}},
      "diagram":{
        "objects":[{
            "id":"1821ab6eea004513b061fb3aaa34807b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":2000,
                "height":100},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3bfc5bb18d4044fcafe4322f50ed83d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "size":{
                    "width":2000,
                    "height":100},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页（新）/u60.png"}},
{
            "id":"c4e8ce9ccacd42b79e2d44b619262fc6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":260,
                "y":10},
              "size":{
                "width":80,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ff364c73fa734d488d3f95012d9de738",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":260,
                    "y":10},
                  "size":{
                    "width":80,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页（新）/u62.png"}},
{
            "id":"5b9fb65a74544ef1bb7174c29a60cf33",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":340,
                "y":30},
              "size":{
                "width":97,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"89b7bc5ad7e448f6a39423d68a75b281",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":340,
                    "y":30},
                  "size":{
                    "width":97,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5493edf72eac416e8d507c5bf9a3a54a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":500,
                "y":37},
              "size":{
                "width":41,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e04a737dd06a42dbb80844f1e2ce75d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":500,
                    "y":37},
                  "size":{
                    "width":41,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（新）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（新）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7020ea293ef94676b8b39c2cc702250a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":581,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24629670b3e34032a452acd4dfe4ecb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":581,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 账户总览",
                        "target":{
                          "targetType":"page",
                          "url":"账户总览.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"95d40ea0e0d04411a1f93c924484046c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":840,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9d067be757bc4d9eb55a68f2214e3ab6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":840,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"case1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 帮助中心",
                        "target":{
                          "targetType":"page",
                          "url":"帮助中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cce804af75f845aaaef9cf4ea298aa28",
            "label":"标题登录按钮",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":970,
                "y":37},
              "size":{
                "width":245,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e77319d89004f1a88255ae1719600a0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":970,
                    "y":37},
                  "size":{
                    "width":245,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"2",
                        "stos":[]}},
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]},
{
                    "description":"Case 2<br> (Else If 值于 Login == &quot;1&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}},
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"2",
                        "stos":[]}},
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"显示 退出登录按钮",
                        "objectsToFades":[{
                            "objectPath":["117de39a6b174043ab639e4de8e4f32b"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f8ae19a9cdd744518715d4848eb273d4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":702,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7bd1fee1ab164844b5cb5814b7d21eb0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":702,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 积分商城（caili）",
                        "target":{
                          "targetType":"page",
                          "url":"积分商城（caili）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"117de39a6b174043ab639e4de8e4f32b",
            "label":"退出登录按钮",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":968,
                "y":74},
              "size":{
                "width":70,
                "height":70},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 值于 Login = &quot;1&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"Login"},
{
                                  "exprType":"stringLiteral",
                                  "value":"1",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（新）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（新）.html",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"fadeWidget",
                        "description":"隐藏 This",
                        "objectsToFades":[{
                            "objectPath":["117de39a6b174043ab639e4de8e4f32b"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"094f13922d86494393e52aeae360066d",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"34968a8b32ae4822b5b6e14742aa4f37",
                    "label":"",
                    "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"67d700fd08904918b4738f1d0e6d4d71",
                        "label":"",
                        "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"5465cbdd1fca49f3927ee512d77e43bc",
                            "label":"",
                            "isContained":true,
                            "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'微软雅黑 Regular', '微软雅黑'",
                              "fontWeight":"400",
                              "fontStyle":"normal",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "size":{
                                "width":70,
                                "height":40}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/首页（新）/u78.png"}}]}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}},
    "b57e6da4c0f649ea8c38ffffca6bde22":{
      "packageId":"b57e6da4c0f649ea8c38ffffca6bde22",
      "type":"Axure:Master",
      "name":"foot",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"45784cc34d2243668a240874e0be3625",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "location":{
                "x":-61,
                "y":244},
              "size":{
                "width":1500,
                "height":200}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cb36fade8eda427092d916bd825567ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "location":{
                    "x":-61,
                    "y":244},
                  "size":{
                    "width":1500,
                    "height":200}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页（新）/u234.png"}},
{
            "id":"eb14d540577d4325aef6c8a52dcc111c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":444,
                "y":280},
              "size":{
                "width":394,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f19d5fd6f5d4454f95b2b7e119099e88",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":444,
                    "y":280},
                  "size":{
                    "width":394,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f9cd1eb4f29b428eb0c2df9bdb23fcf0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":545,
                "y":324},
              "size":{
                "width":289,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59bf2f5a09994af893cf0d2cefb2564a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":545,
                    "y":324},
                  "size":{
                    "width":289,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8187b68a46584b3e8e8633bc4d28a79a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":377,
                "y":384},
              "size":{
                "width":623,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2582237d217c46bf878e7852b877a1a6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":377,
                    "y":384},
                  "size":{
                    "width":623,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"869bf3c4952e4e4fa146f90d1b21e694",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":870,
                "y":280},
              "size":{
                "width":73,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9483d61963448a2896b12b59d1e4e5a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":870,
                    "y":280},
                  "size":{
                    "width":73,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 规则协议列表",
                        "target":{
                          "targetType":"page",
                          "url":"规则协议列表.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "9cea0dc7b38c4ccc957a577b80edcc9d":{
      "scriptId":"u0"},
    "e44fb9f04ea841d2bccc7a1f6beac8c5":{
      "scriptId":"u1"},
    "b6c8afd032bb49639d55f70f336a49ff":{
      "scriptId":"u2"},
    "94458dbd0baf4d4bba571d1920791261":{
      "scriptId":"u3"},
    "b8ec6d74f33d4292af5c4541dc88640d":{
      "scriptId":"u4"},
    "76251edecdfa42fc9fb37fcedab389bb":{
      "scriptId":"u5"},
    "37da911f369249bf812dc928eb3d1d3f":{
      "scriptId":"u6"},
    "3b976c0e24d346c5a157e8695b63c0b9":{
      "scriptId":"u7"},
    "cbc708b0c4fe4892bfaec56712d3275c":{
      "scriptId":"u8"},
    "4be36a887982443ab160fdeccb0ed00c":{
      "scriptId":"u9"},
    "9f6db67f99734f88a3fa82d5f58a5b9b":{
      "scriptId":"u10"},
    "ff03a182722c4c89b616a0c306f09e32":{
      "scriptId":"u11"},
    "48db2ae47e104e48b69d25d3a2b61adc":{
      "scriptId":"u12"},
    "29bf3f2b1fe04581b39c43f5c133f84c":{
      "scriptId":"u13"},
    "e952bc1aecff462b969144841e1b28d7":{
      "scriptId":"u14"},
    "7a36ac84088948d4bb4522411f31219f":{
      "scriptId":"u15"},
    "366052cf94dc4d1bb4f144e34169591e":{
      "scriptId":"u16"},
    "466936ff82664baf9f1009390e9c3be3":{
      "scriptId":"u17"},
    "eb4223973be147e58ba75d8978e1b777":{
      "scriptId":"u18"},
    "7914748997724bbba3a15d14cb5c8117":{
      "scriptId":"u19"},
    "4c361a22f1af46678640f7169ba9268e":{
      "scriptId":"u20"},
    "7a5fa38960794c09a0f5db7b48efaa0c":{
      "scriptId":"u21"},
    "939de69799b441dc8569cbff4ad0342b":{
      "scriptId":"u22"},
    "f9369bb11b7b44e2904f4b23e00802fd":{
      "scriptId":"u23"},
    "62d8b1a60f3846528bbb8f923aff0766":{
      "scriptId":"u24"},
    "06dbf868b64c4867bc1337bd33bcff7f":{
      "scriptId":"u25"},
    "c47f415487c14e888643aeeaa6aea655":{
      "scriptId":"u26"},
    "d7e236feebc34cbe86c67bd311679431":{
      "scriptId":"u27"},
    "6b5280cf1d9d4f99bf5f7d8bd4c064fb":{
      "scriptId":"u28"},
    "86c7dbbb2acd4e5fadf3ee7c887ebc1d":{
      "scriptId":"u29"},
    "34acab0d4e2b41a58f54dc46ae494391":{
      "scriptId":"u30"},
    "538fa9b152d14b80b3c875332f6c167d":{
      "scriptId":"u31"},
    "1d515e62b3674826b1273fa5acf7b398":{
      "scriptId":"u32"},
    "ddc962957efd4f6ea49f21679c4111f8":{
      "scriptId":"u33"},
    "b934ecfb31cc4b1a9d9f080213016dc2":{
      "scriptId":"u34"},
    "4fe8ebbd3dc743f09dc92b8e984023e9":{
      "scriptId":"u35"},
    "849b8bf109804d32bef9cd41103d6fb5":{
      "scriptId":"u36"},
    "188c659962a84b438785c5ccacf05cda":{
      "scriptId":"u37"},
    "2b5f00055c874a0aac769fce3afaeec2":{
      "scriptId":"u38"},
    "85747caef489432ba3578300ddc17582":{
      "scriptId":"u39"},
    "580a72cab52f4321b63e56031346a833":{
      "scriptId":"u40"},
    "8b52a103c5d247e6968f5516d9f31ef3":{
      "scriptId":"u41"},
    "4c9066ae4a774684b452d1cd92062ecf":{
      "scriptId":"u42"},
    "d153bc5a85a94bababfc07002bfdd8b5":{
      "scriptId":"u43"},
    "4d06950dd5b44f24b9c2f9654b735f81":{
      "scriptId":"u44"},
    "0cc79d779b8043989cefcc40cae263df":{
      "scriptId":"u45",
      "1821ab6eea004513b061fb3aaa34807b":{
        "scriptId":"u46"},
      "3bfc5bb18d4044fcafe4322f50ed83d9":{
        "scriptId":"u47"},
      "c4e8ce9ccacd42b79e2d44b619262fc6":{
        "scriptId":"u48"},
      "ff364c73fa734d488d3f95012d9de738":{
        "scriptId":"u49"},
      "5b9fb65a74544ef1bb7174c29a60cf33":{
        "scriptId":"u50"},
      "89b7bc5ad7e448f6a39423d68a75b281":{
        "scriptId":"u51"},
      "5493edf72eac416e8d507c5bf9a3a54a":{
        "scriptId":"u52"},
      "e04a737dd06a42dbb80844f1e2ce75d3":{
        "scriptId":"u53"},
      "7020ea293ef94676b8b39c2cc702250a":{
        "scriptId":"u54"},
      "24629670b3e34032a452acd4dfe4ecb1":{
        "scriptId":"u55"},
      "95d40ea0e0d04411a1f93c924484046c":{
        "scriptId":"u56"},
      "9d067be757bc4d9eb55a68f2214e3ab6":{
        "scriptId":"u57"},
      "cce804af75f845aaaef9cf4ea298aa28":{
        "scriptId":"u58"},
      "6e77319d89004f1a88255ae1719600a0":{
        "scriptId":"u59"},
      "f8ae19a9cdd744518715d4848eb273d4":{
        "scriptId":"u60"},
      "7bd1fee1ab164844b5cb5814b7d21eb0":{
        "scriptId":"u61"},
      "117de39a6b174043ab639e4de8e4f32b":{
        "scriptId":"u62"},
      "34968a8b32ae4822b5b6e14742aa4f37":{
        "scriptId":"u63"},
      "67d700fd08904918b4738f1d0e6d4d71":{
        "scriptId":"u64"},
      "5465cbdd1fca49f3927ee512d77e43bc":{
        "scriptId":"u65"}},
    "c8b61cd01370453a837ff9c03c579fb1":{
      "scriptId":"u66",
      "45784cc34d2243668a240874e0be3625":{
        "scriptId":"u67"},
      "cb36fade8eda427092d916bd825567ca":{
        "scriptId":"u68"},
      "eb14d540577d4325aef6c8a52dcc111c":{
        "scriptId":"u69"},
      "f19d5fd6f5d4454f95b2b7e119099e88":{
        "scriptId":"u70"},
      "f9cd1eb4f29b428eb0c2df9bdb23fcf0":{
        "scriptId":"u71"},
      "59bf2f5a09994af893cf0d2cefb2564a":{
        "scriptId":"u72"},
      "8187b68a46584b3e8e8633bc4d28a79a":{
        "scriptId":"u73"},
      "2582237d217c46bf878e7852b877a1a6":{
        "scriptId":"u74"},
      "869bf3c4952e4e4fa146f90d1b21e694":{
        "scriptId":"u75"},
      "b9483d61963448a2896b12b59d1e4e5a":{
        "scriptId":"u76"}},
    "e3ebc0580f404b5aab930055669c2fc1":{
      "scriptId":"u77"},
    "7e73e111a4284a0b87fe711be6f22c60":{
      "scriptId":"u78"}}});