$axure.loadCurrentPage({
  "url":"提现.html",
  "generationDate":new Date(1441088583768.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"daojishi",
"shuzi",
"Login"],
  "page":{
    "packageId":"7510f03a63054e7a87728793f6093a07",
    "type":"Axure:Page",
    "name":"提现",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFF2F2F2},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"42d796b8eadc462a90b2a31358417d57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":159,
              "y":124},
            "size":{
              "width":1560,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e79e671c3916473b900cc57e02401100",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":159,
                  "y":124},
                "size":{
                  "width":1560,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户总览/u0.png"}},
{
          "id":"09bbe09b870f42dcbd22491e5acd9c85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":419,
              "y":129},
            "size":{
              "width":163,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df99bf5b9f234c93910a9feb811bae41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":419,
                  "y":129},
                "size":{
                  "width":163,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3de6d682f5bb482daf1857f6455787c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":638,
              "y":170},
            "size":{
              "width":779,
              "height":898},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3afd8e513b8472a93401487dad0a480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":638,
                  "y":170},
                "size":{
                  "width":779,
                  "height":898},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的积分/u4.png"}},
{
          "id":"70e329cb99fc40cca59d15da90a27afa",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":638,
              "y":222},
            "size":{
              "width":779,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/账户总览/u6_line.png"}},
{
          "id":"7629276ab84243de893b8320317316f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":665,
              "y":189},
            "size":{
              "width":33,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"371fb571891c4f6787e0c5229900ff4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":665,
                  "y":189},
                "size":{
                  "width":33,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f3eb09f55f746e1a6818f85fdce11eb",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":1104}},
          "adaptiveStyles":{
},
          "masterId":"b57e6da4c0f649ea8c38ffffca6bde22"},
{
          "id":"067ccd352f48452cb105174f269317f7",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":417,
              "y":170}},
          "adaptiveStyles":{
},
          "masterId":"976d6fcdccbd4c0ebb7218ce9c6a60b2"},
{
          "id":"067165b4ccab4ebbb162be67d4bbe4cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":646,
              "y":237},
            "size":{
              "width":652,
              "height":554}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65b8196e06b64ec2a6072af39e13c595",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":646,
                  "y":237},
                "size":{
                  "width":652,
                  "height":554}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现/u49.png"}},
{
          "id":"db3689e1742943ccb146a7c6e3192066",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":722,
              "y":418},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d406ba934b8d46e68d81a595750040ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":722,
                  "y":418},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现/u51.png"}},
{
          "id":"d17aa11a5b9e4517b6852eb5e9fdee72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":699,
              "y":405},
            "size":{
              "width":96,
              "height":46},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601a65fa2fb246ac84de48c59753cd1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":699,
                  "y":405},
                "size":{
                  "width":96,
                  "height":46},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现/u53.png"}},
{
          "id":"de1012795fe1487aa47e7d38d8d702e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":652,
              "y":392},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cf49ea5067147a19135afda6df53de0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":652,
                  "y":392},
                "size":{
                  "width":60,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"849221c5f3b04fdf8f3b25b1d346d5c4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":655,
              "y":451},
            "size":{
              "width":715,
              "height":396}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ebb01c77506404d9ce8a0fa8e900801",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":655,
                  "y":451},
                "size":{
                  "width":715,
                  "height":396}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提现/u57.png"}},
{
          "id":"cbe12d5386b0475c993c8151117f913f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":909,
              "y":431},
            "size":{
              "width":169,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"953790b75f5b4498ace08024c2d53b5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":909,
                  "y":431},
                "size":{
                  "width":169,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e31d728b3ef349c7828b4ebb9326ac84",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"30a1e3ad2c17482a9dbf4657c7395ef2"}]}},
  "masters":{
    "b57e6da4c0f649ea8c38ffffca6bde22":{
      "packageId":"b57e6da4c0f649ea8c38ffffca6bde22",
      "type":"Axure:Master",
      "name":"foot",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"45784cc34d2243668a240874e0be3625",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "location":{
                "x":-61,
                "y":244},
              "size":{
                "width":1500,
                "height":200}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cb36fade8eda427092d916bd825567ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "location":{
                    "x":-61,
                    "y":244},
                  "size":{
                    "width":1500,
                    "height":200}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页（新）/u234.png"}},
{
            "id":"eb14d540577d4325aef6c8a52dcc111c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":444,
                "y":280},
              "size":{
                "width":394,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f19d5fd6f5d4454f95b2b7e119099e88",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":444,
                    "y":280},
                  "size":{
                    "width":394,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f9cd1eb4f29b428eb0c2df9bdb23fcf0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":545,
                "y":324},
              "size":{
                "width":289,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59bf2f5a09994af893cf0d2cefb2564a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":545,
                    "y":324},
                  "size":{
                    "width":289,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8187b68a46584b3e8e8633bc4d28a79a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":377,
                "y":384},
              "size":{
                "width":623,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2582237d217c46bf878e7852b877a1a6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":377,
                    "y":384},
                  "size":{
                    "width":623,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"869bf3c4952e4e4fa146f90d1b21e694",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":870,
                "y":280},
              "size":{
                "width":73,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9483d61963448a2896b12b59d1e4e5a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":870,
                    "y":280},
                  "size":{
                    "width":73,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 规则协议列表",
                        "target":{
                          "targetType":"page",
                          "url":"规则协议列表.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "976d6fcdccbd4c0ebb7218ce9c6a60b2":{
      "packageId":"976d6fcdccbd4c0ebb7218ce9c6a60b2",
      "type":"Axure:Master",
      "name":"个账中心菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"336c6db3a5f547c1a5c495bdd9d140c2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFFFF},
              "location":{
                "x":427,
                "y":180},
              "size":{
                "width":211,
                "height":891},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"77a1a7c7e14d4437a9cd2519711b7643",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF},
                  "location":{
                    "x":427,
                    "y":180},
                  "size":{
                    "width":211,
                    "height":891},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/账户总览/u67.png"}},
{
            "id":"f7e738347337486581aa5b5b60ebd7ed",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":452,
                "y":212},
              "size":{
                "width":140,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7235ced95cb94b1f95441ede33dd1bb7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":452,
                    "y":212},
                  "size":{
                    "width":140,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2ecc0e915f474d99a94cc79be27c896a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":452,
                "y":505},
              "size":{
                "width":140,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ac83a7d613f74483875fd78ff2aea27c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":452,
                    "y":505},
                  "size":{
                    "width":140,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 积分兑换",
                        "target":{
                          "targetType":"page",
                          "url":"积分兑换.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3e5b05fb3ef34743aa62949f43b763b3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":488,
                "y":465},
              "size":{
                "width":140,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e99d39366274f929fe21460c09a0681",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":488,
                    "y":465},
                  "size":{
                    "width":140,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 获取积分明细",
                        "target":{
                          "targetType":"page",
                          "url":"获取积分明细.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c15a5046e7794906aa8930dac6710b78",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":473,
                "y":275},
              "size":{
                "width":60,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2aa3168b3bd04a908758368b768418a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":473,
                    "y":275},
                  "size":{
                    "width":60,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的积分",
                        "target":{
                          "targetType":"page",
                          "url":"我的积分.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7a7a2ea42ac249a4a152cb14df5ea88d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":473,
                "y":310},
              "size":{
                "width":60,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f78e45a0e19b46a3bc6b834b0e787490",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":473,
                    "y":310},
                  "size":{
                    "width":60,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的现金",
                        "target":{
                          "targetType":"page",
                          "url":"我的现金.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"bc00a905daf649d183519e2f00acc644",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":473,
                "y":345},
              "size":{
                "width":71,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"07ff0a685d00470dbf7b35549067d2f4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":473,
                    "y":345},
                  "size":{
                    "width":71,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1633860c0fce459dbe332bf90ecd6d06",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":452,
                "y":609},
              "size":{
                "width":140,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"767632f2ac4b4df0a0061b3d64974903",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":452,
                    "y":609},
                  "size":{
                    "width":140,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"1193020757634e57901cf366575a2ff1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":473,
                "y":647},
              "size":{
                "width":60,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f174dc01a76a4487a7634dbf403178f0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":473,
                    "y":647},
                  "size":{
                    "width":60,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c2bf48ef43db4067852197106bcf28f6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":474,
                "y":680},
              "size":{
                "width":71,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1f135456232a475ea41a57dd395a77d5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":474,
                    "y":680},
                  "size":{
                    "width":71,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 银行卡管理",
                        "target":{
                          "targetType":"page",
                          "url":"银行卡管理.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"454c48c12c0742a2a669e7d0ecf655f6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":488,
                "y":435},
              "size":{
                "width":140,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9497b7838fda4389accf2f8a93c948eb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":488,
                    "y":435},
                  "size":{
                    "width":140,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 已邀请好友",
                        "target":{
                          "targetType":"page",
                          "url":"已邀请好友.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"dbd4ad78ba4341bcb325632dcb399515",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":452,
                "y":554},
              "size":{
                "width":140,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"956225339f274b5c9fedffbcb07a4f45",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":452,
                    "y":554},
                  "size":{
                    "width":140,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 推广明细",
                        "target":{
                          "targetType":"page",
                          "url":"推广明细.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"29841f0d99c44e38aac539df0d4bc8b9",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Bold', '微软雅黑'",
              "fontSize":"14px",
              "fontWeight":"700",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF000000,
                "opacity":1},
              "location":{
                "x":473,
                "y":245},
              "size":{
                "width":60,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"56837397719640108649de15d3de33ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Bold', '微软雅黑'",
                  "fontSize":"14px",
                  "fontWeight":"700",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1},
                  "location":{
                    "x":473,
                    "y":245},
                  "size":{
                    "width":60,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 账户总览",
                        "target":{
                          "targetType":"page",
                          "url":"账户总览.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3206ad2d2c334ce6b3212c8afaf503e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":452,
                "y":399},
              "size":{
                "width":140,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ba7e21cdd0b649f8bb1d49aaa1fea403",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":452,
                    "y":399},
                  "size":{
                    "width":140,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "30a1e3ad2c17482a9dbf4657c7395ef2":{
      "packageId":"30a1e3ad2c17482a9dbf4657c7395ef2",
      "type":"Axure:Master",
      "name":"首页Tittle",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
        "onLoad":{
          "description":"OnLoad",
          "cases":[{
              "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
              "isNewIfGroup":false,
              "condition":{
                "exprType":"binaryOp",
                "op":"==",
                "leftExpr":{
                  "exprType":"fcall",
                  "functionName":"GetGlobalVariableValue",
                  "arguments":[{
                      "exprType":"globalVariableLiteral",
                      "variableName":"Login"}]},
                "rightExpr":{
                  "exprType":"stringLiteral",
                  "value":"2",
                  "stos":[]}},
              "actions":[{
                  "action":"setFunction",
                  "description":"设置 文字于 标题登录按钮 = &quot;18583632736(积分 1454)&quot;",
                  "expr":{
                    "exprType":"block",
                    "subExprs":[{
                        "exprType":"fcall",
                        "functionName":"SetWidgetRichText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["6e77319d89004f1a88255ae1719600a0"]},
{
                            "exprType":"stringLiteral",
                            "value":"18583632736(积分 1454)",
                            "stos":[]},
{
                            "exprType":"booleanLiteral",
                            "value":true}]}]}}]}]}},
      "diagram":{
        "objects":[{
            "id":"1821ab6eea004513b061fb3aaa34807b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "size":{
                "width":2000,
                "height":100},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3bfc5bb18d4044fcafe4322f50ed83d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "size":{
                    "width":2000,
                    "height":100},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页（新）/u60.png"}},
{
            "id":"c4e8ce9ccacd42b79e2d44b619262fc6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":260,
                "y":10},
              "size":{
                "width":80,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ff364c73fa734d488d3f95012d9de738",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":260,
                    "y":10},
                  "size":{
                    "width":80,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页（新）/u62.png"}},
{
            "id":"5b9fb65a74544ef1bb7174c29a60cf33",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":340,
                "y":30},
              "size":{
                "width":97,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"89b7bc5ad7e448f6a39423d68a75b281",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":340,
                    "y":30},
                  "size":{
                    "width":97,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5493edf72eac416e8d507c5bf9a3a54a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":500,
                "y":37},
              "size":{
                "width":41,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e04a737dd06a42dbb80844f1e2ce75d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":500,
                    "y":37},
                  "size":{
                    "width":41,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（新）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（新）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7020ea293ef94676b8b39c2cc702250a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":581,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24629670b3e34032a452acd4dfe4ecb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":581,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 账户总览",
                        "target":{
                          "targetType":"page",
                          "url":"账户总览.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"95d40ea0e0d04411a1f93c924484046c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":840,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9d067be757bc4d9eb55a68f2214e3ab6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":840,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"case1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 帮助中心",
                        "target":{
                          "targetType":"page",
                          "url":"帮助中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cce804af75f845aaaef9cf4ea298aa28",
            "label":"标题登录按钮",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":970,
                "y":37},
              "size":{
                "width":245,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e77319d89004f1a88255ae1719600a0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":970,
                    "y":37},
                  "size":{
                    "width":245,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"2",
                        "stos":[]}},
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]},
{
                    "description":"Case 2<br> (Else If 值于 Login == &quot;1&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}},
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"2",
                        "stos":[]}},
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"显示 退出登录按钮",
                        "objectsToFades":[{
                            "objectPath":["117de39a6b174043ab639e4de8e4f32b"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f8ae19a9cdd744518715d4848eb273d4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "location":{
                "x":702,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7bd1fee1ab164844b5cb5814b7d21eb0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "location":{
                    "x":702,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 2",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 积分商城（caili）",
                        "target":{
                          "targetType":"page",
                          "url":"积分商城（caili）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"117de39a6b174043ab639e4de8e4f32b",
            "label":"退出登录按钮",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":968,
                "y":74},
              "size":{
                "width":70,
                "height":70},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 值于 Login = &quot;1&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"Login"},
{
                                  "exprType":"stringLiteral",
                                  "value":"1",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页（新）",
                        "target":{
                          "targetType":"page",
                          "url":"首页（新）.html",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"fadeWidget",
                        "description":"隐藏 This",
                        "objectsToFades":[{
                            "objectPath":["117de39a6b174043ab639e4de8e4f32b"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"094f13922d86494393e52aeae360066d",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"34968a8b32ae4822b5b6e14742aa4f37",
                    "label":"",
                    "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"67d700fd08904918b4738f1d0e6d4d71",
                        "label":"",
                        "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"5465cbdd1fca49f3927ee512d77e43bc",
                            "label":"",
                            "isContained":true,
                            "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'微软雅黑 Regular', '微软雅黑'",
                              "fontWeight":"400",
                              "fontStyle":"normal",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "size":{
                                "width":70,
                                "height":40}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/首页（新）/u78.png"}}]}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}}},
  "objectPaths":{
    "42d796b8eadc462a90b2a31358417d57":{
      "scriptId":"u0"},
    "e79e671c3916473b900cc57e02401100":{
      "scriptId":"u1"},
    "09bbe09b870f42dcbd22491e5acd9c85":{
      "scriptId":"u2"},
    "df99bf5b9f234c93910a9feb811bae41":{
      "scriptId":"u3"},
    "3de6d682f5bb482daf1857f6455787c1":{
      "scriptId":"u4"},
    "f3afd8e513b8472a93401487dad0a480":{
      "scriptId":"u5"},
    "70e329cb99fc40cca59d15da90a27afa":{
      "scriptId":"u6"},
    "7629276ab84243de893b8320317316f5":{
      "scriptId":"u7"},
    "371fb571891c4f6787e0c5229900ff4b":{
      "scriptId":"u8"},
    "7f3eb09f55f746e1a6818f85fdce11eb":{
      "scriptId":"u9",
      "45784cc34d2243668a240874e0be3625":{
        "scriptId":"u10"},
      "cb36fade8eda427092d916bd825567ca":{
        "scriptId":"u11"},
      "eb14d540577d4325aef6c8a52dcc111c":{
        "scriptId":"u12"},
      "f19d5fd6f5d4454f95b2b7e119099e88":{
        "scriptId":"u13"},
      "f9cd1eb4f29b428eb0c2df9bdb23fcf0":{
        "scriptId":"u14"},
      "59bf2f5a09994af893cf0d2cefb2564a":{
        "scriptId":"u15"},
      "8187b68a46584b3e8e8633bc4d28a79a":{
        "scriptId":"u16"},
      "2582237d217c46bf878e7852b877a1a6":{
        "scriptId":"u17"},
      "869bf3c4952e4e4fa146f90d1b21e694":{
        "scriptId":"u18"},
      "b9483d61963448a2896b12b59d1e4e5a":{
        "scriptId":"u19"}},
    "067ccd352f48452cb105174f269317f7":{
      "scriptId":"u20",
      "336c6db3a5f547c1a5c495bdd9d140c2":{
        "scriptId":"u21"},
      "77a1a7c7e14d4437a9cd2519711b7643":{
        "scriptId":"u22"},
      "f7e738347337486581aa5b5b60ebd7ed":{
        "scriptId":"u23"},
      "7235ced95cb94b1f95441ede33dd1bb7":{
        "scriptId":"u24"},
      "2ecc0e915f474d99a94cc79be27c896a":{
        "scriptId":"u25"},
      "ac83a7d613f74483875fd78ff2aea27c":{
        "scriptId":"u26"},
      "3e5b05fb3ef34743aa62949f43b763b3":{
        "scriptId":"u27"},
      "6e99d39366274f929fe21460c09a0681":{
        "scriptId":"u28"},
      "c15a5046e7794906aa8930dac6710b78":{
        "scriptId":"u29"},
      "2aa3168b3bd04a908758368b768418a8":{
        "scriptId":"u30"},
      "7a7a2ea42ac249a4a152cb14df5ea88d":{
        "scriptId":"u31"},
      "f78e45a0e19b46a3bc6b834b0e787490":{
        "scriptId":"u32"},
      "bc00a905daf649d183519e2f00acc644":{
        "scriptId":"u33"},
      "07ff0a685d00470dbf7b35549067d2f4":{
        "scriptId":"u34"},
      "1633860c0fce459dbe332bf90ecd6d06":{
        "scriptId":"u35"},
      "767632f2ac4b4df0a0061b3d64974903":{
        "scriptId":"u36"},
      "1193020757634e57901cf366575a2ff1":{
        "scriptId":"u37"},
      "f174dc01a76a4487a7634dbf403178f0":{
        "scriptId":"u38"},
      "c2bf48ef43db4067852197106bcf28f6":{
        "scriptId":"u39"},
      "1f135456232a475ea41a57dd395a77d5":{
        "scriptId":"u40"},
      "454c48c12c0742a2a669e7d0ecf655f6":{
        "scriptId":"u41"},
      "9497b7838fda4389accf2f8a93c948eb":{
        "scriptId":"u42"},
      "dbd4ad78ba4341bcb325632dcb399515":{
        "scriptId":"u43"},
      "956225339f274b5c9fedffbcb07a4f45":{
        "scriptId":"u44"},
      "29841f0d99c44e38aac539df0d4bc8b9":{
        "scriptId":"u45"},
      "56837397719640108649de15d3de33ca":{
        "scriptId":"u46"},
      "3206ad2d2c334ce6b3212c8afaf503e2":{
        "scriptId":"u47"},
      "ba7e21cdd0b649f8bb1d49aaa1fea403":{
        "scriptId":"u48"}},
    "067165b4ccab4ebbb162be67d4bbe4cb":{
      "scriptId":"u49"},
    "65b8196e06b64ec2a6072af39e13c595":{
      "scriptId":"u50"},
    "db3689e1742943ccb146a7c6e3192066":{
      "scriptId":"u51"},
    "d406ba934b8d46e68d81a595750040ba":{
      "scriptId":"u52"},
    "d17aa11a5b9e4517b6852eb5e9fdee72":{
      "scriptId":"u53"},
    "601a65fa2fb246ac84de48c59753cd1c":{
      "scriptId":"u54"},
    "de1012795fe1487aa47e7d38d8d702e2":{
      "scriptId":"u55"},
    "6cf49ea5067147a19135afda6df53de0":{
      "scriptId":"u56"},
    "849221c5f3b04fdf8f3b25b1d346d5c4":{
      "scriptId":"u57"},
    "2ebb01c77506404d9ce8a0fa8e900801":{
      "scriptId":"u58"},
    "cbe12d5386b0475c993c8151117f913f":{
      "scriptId":"u59"},
    "953790b75f5b4498ace08024c2d53b5f":{
      "scriptId":"u60"},
    "e31d728b3ef349c7828b4ebb9326ac84":{
      "scriptId":"u61",
      "1821ab6eea004513b061fb3aaa34807b":{
        "scriptId":"u62"},
      "3bfc5bb18d4044fcafe4322f50ed83d9":{
        "scriptId":"u63"},
      "c4e8ce9ccacd42b79e2d44b619262fc6":{
        "scriptId":"u64"},
      "ff364c73fa734d488d3f95012d9de738":{
        "scriptId":"u65"},
      "5b9fb65a74544ef1bb7174c29a60cf33":{
        "scriptId":"u66"},
      "89b7bc5ad7e448f6a39423d68a75b281":{
        "scriptId":"u67"},
      "5493edf72eac416e8d507c5bf9a3a54a":{
        "scriptId":"u68"},
      "e04a737dd06a42dbb80844f1e2ce75d3":{
        "scriptId":"u69"},
      "7020ea293ef94676b8b39c2cc702250a":{
        "scriptId":"u70"},
      "24629670b3e34032a452acd4dfe4ecb1":{
        "scriptId":"u71"},
      "95d40ea0e0d04411a1f93c924484046c":{
        "scriptId":"u72"},
      "9d067be757bc4d9eb55a68f2214e3ab6":{
        "scriptId":"u73"},
      "cce804af75f845aaaef9cf4ea298aa28":{
        "scriptId":"u74"},
      "6e77319d89004f1a88255ae1719600a0":{
        "scriptId":"u75"},
      "f8ae19a9cdd744518715d4848eb273d4":{
        "scriptId":"u76"},
      "7bd1fee1ab164844b5cb5814b7d21eb0":{
        "scriptId":"u77"},
      "117de39a6b174043ab639e4de8e4f32b":{
        "scriptId":"u78"},
      "34968a8b32ae4822b5b6e14742aa4f37":{
        "scriptId":"u79"},
      "67d700fd08904918b4738f1d0e6d4d71":{
        "scriptId":"u80"},
      "5465cbdd1fca49f3927ee512d77e43bc":{
        "scriptId":"u81"}}}});