$axure.loadCurrentPage({
  "url":"忘记密码.html",
  "generationDate":new Date(1440052781468.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"daojishi",
"shuzi",
"Login"],
  "page":{
    "packageId":"6ca8b47fd18a497aa4a4021be7fc2fe3",
    "type":"Axure:Page",
    "name":"忘记密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFCCCCCC},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"微软雅黑",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c93526a45f57476898b54215fe99e4de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":250,
              "y":170},
            "size":{
              "width":1000,
              "height":491},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c9a8d379f8a45eaa830fb804fee886e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":250,
                  "y":170},
                "size":{
                  "width":1000,
                  "height":491},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u0.png"}},
{
          "id":"e009010d79354c748a6722b498ebb3dc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"cca190e769a3445c9ed90be183fb7090"},
{
          "id":"803f05126d234deca2008e0a0539c43b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":0,
              "y":130},
            "size":{
              "width":1500,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89b6f2dddf804d888b8770e71a376268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":0,
                  "y":130},
                "size":{
                  "width":1500,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u37.png"}},
{
          "id":"c44cea64f75b4ce48842ec7b79699051",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":496,
              "y":231},
            "size":{
              "width":97,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bff3bf2d9c64114bd4cab43486a011f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":496,
                  "y":231},
                "size":{
                  "width":97,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f06ab9bb9fda42a285309ab5fc5303d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":347,
              "y":320},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87a8aa52b145491e8cc7faeea7e27413",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":347,
                  "y":320},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a027649fe63344f896e49179714b81fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":347,
              "y":379},
            "size":{
              "width":43,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e00bf03341374f5fbfb6b90c5d90ffaf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":347,
                  "y":379},
                "size":{
                  "width":43,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c0f28b7ef4340968edb12d108a05a9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":544,
              "y":363},
            "size":{
              "width":148,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb6cc0be4484428eb80a58e887879d05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":544,
                  "y":363},
                "size":{
                  "width":148,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u39.png"}},
{
          "id":"975efaa1aba8443299d257d08109b66f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":337,
              "y":432},
            "size":{
              "width":70,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfb058ed614b4d3c9e8a9496eaff64ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":337,
                  "y":432},
                "size":{
                  "width":70,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a19ddf4cff554a1baace60f8b84bba06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":260,
              "y":135},
            "size":{
              "width":163,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4ee080eab3244608336578deae30d2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":260,
                  "y":135},
                "size":{
                  "width":163,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"901437d62fde4b68a8caffdcdf65b91a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":417,
              "y":320},
            "size":{
              "width":260,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea2b1f479d57442a9c8ef762bffac253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":417,
                  "y":320},
                "size":{
                  "width":260,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u39.png"}},
{
          "id":"e46346f7c87c4500b5cd9a9e9f808bb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":417,
              "y":372},
            "size":{
              "width":117,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"650aaf5c5074481fa513ab861872b05d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":417,
                  "y":372},
                "size":{
                  "width":117,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u41.png"}},
{
          "id":"38b9a30fdf9146cca21445c3a03024cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "location":{
              "x":417,
              "y":425},
            "size":{
              "width":117,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85bcf15880de441a9cde0b06a707e155",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "location":{
                  "x":417,
                  "y":425},
                "size":{
                  "width":117,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/忘记密码/u41.png"}},
{
          "id":"9ab17c14e8b94dc3802e16e67c669e37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":551,
              "y":425},
            "size":{
              "width":126,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e95d1336a1ce417e9066c7b476769974",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":551,
                  "y":425},
                "size":{
                  "width":126,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u74.png"}},
{
          "id":"cf340e29b70744d591849aca639fb3ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "opacity":"0.8",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":417,
              "y":504},
            "size":{
              "width":260,
              "height":35},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f97a14d5d9f4f5fae148189a3589faa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "opacity":"0.8",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":417,
                  "y":504},
                "size":{
                  "width":260,
                  "height":35},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/忘记密码/u47.png"}},
{
          "id":"f114661b59014d8c917ec3a4627d6af9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":832,
              "y":224.5},
            "size":{
              "width":10,
              "height":337},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录/u45_line.png"}},
{
          "id":"fdf60de0d076470d9d644b650aae72e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fontStyle":"normal",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":892,
              "y":224},
            "size":{
              "width":319,
              "height":331},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be82d903542f4dd8b2c90a00bd9f95c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":892,
                  "y":224},
                "size":{
                  "width":319,
                  "height":331},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u46.png"}},
{
          "id":"83475e486b484fa58c37e41f4bcabaf3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":693}},
          "adaptiveStyles":{
},
          "masterId":"36acf1ef35a04a2486fa269800e377cb"}]}},
  "masters":{
    "cca190e769a3445c9ed90be183fb7090":{
      "packageId":"cca190e769a3445c9ed90be183fb7090",
      "type":"Axure:Master",
      "name":"首页Tittle",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
        "onLoad":{
          "description":"OnLoad",
          "cases":[{
              "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
              "isNewIfGroup":false,
              "condition":{
                "exprType":"binaryOp",
                "op":"==",
                "leftExpr":{
                  "exprType":"fcall",
                  "functionName":"GetGlobalVariableValue",
                  "arguments":[{
                      "exprType":"globalVariableLiteral",
                      "variableName":"Login"}]},
                "rightExpr":{
                  "exprType":"stringLiteral",
                  "value":"2",
                  "stos":[]}},
              "actions":[{
                  "action":"setFunction",
                  "description":"设置 文字于 标题登录按钮 = &quot;18583632736(积分 1454)&quot;",
                  "expr":{
                    "exprType":"block",
                    "subExprs":[{
                        "exprType":"fcall",
                        "functionName":"SetWidgetRichText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["6e77319d89004f1a88255ae1719600a0"]},
{
                            "exprType":"stringLiteral",
                            "value":"18583632736(积分 1454)",
                            "stos":[]},
{
                            "exprType":"booleanLiteral",
                            "value":true}]}]}}]}]}},
      "diagram":{
        "objects":[{
            "id":"1821ab6eea004513b061fb3aaa34807b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "size":{
                "width":2000,
                "height":114},
              "borderWidth":"-1"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3bfc5bb18d4044fcafe4322f50ed83d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "size":{
                    "width":2000,
                    "height":114},
                  "borderWidth":"-1"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u15.png"}},
{
            "id":"c4e8ce9ccacd42b79e2d44b619262fc6",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":260,
                "y":10},
              "size":{
                "width":80,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ff364c73fa734d488d3f95012d9de738",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":260,
                    "y":10},
                  "size":{
                    "width":80,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页（新）/u62.png"}},
{
            "id":"5b9fb65a74544ef1bb7174c29a60cf33",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":340,
                "y":30},
              "size":{
                "width":97,
                "height":41}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"89b7bc5ad7e448f6a39423d68a75b281",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":340,
                    "y":30},
                  "size":{
                    "width":97,
                    "height":41}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5493edf72eac416e8d507c5bf9a3a54a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":500,
                "y":37},
              "size":{
                "width":41,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e04a737dd06a42dbb80844f1e2ce75d3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":500,
                    "y":37},
                  "size":{
                    "width":41,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"91d413a8249e4dbe88f0bac22dd6425f",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":823,
                "y":37},
              "size":{
                "width":101,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d09956ae518b4d95892d6b5f7d466693",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":823,
                    "y":37},
                  "size":{
                    "width":101,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 关于钱客栈",
                        "target":{
                          "targetType":"page",
                          "url":"关于钱客栈.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7020ea293ef94676b8b39c2cc702250a",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":581,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"24629670b3e34032a452acd4dfe4ecb1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":581,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"95d40ea0e0d04411a1f93c924484046c",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":964,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9d067be757bc4d9eb55a68f2214e3ab6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":964,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"case1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 帮助中心",
                        "target":{
                          "targetType":"page",
                          "url":"帮助中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cce804af75f845aaaef9cf4ea298aa28",
            "label":"标题登录按钮",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":1085,
                "y":37},
              "size":{
                "width":245,
                "height":37}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e77319d89004f1a88255ae1719600a0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":1085,
                    "y":37},
                  "size":{
                    "width":245,
                    "height":37}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"2",
                        "stos":[]}},
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]},
{
                    "description":"Case 2<br> (Else If 值于 Login == &quot;1&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]}},
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 登录",
                        "target":{
                          "targetType":"page",
                          "url":"登录.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]},
              "onMouseOver":{
                "description":"OnMouseOver",
                "cases":[{
                    "description":"Case 1<br> (If 值于 Login == &quot;2&quot;)",
                    "isNewIfGroup":false,
                    "condition":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetGlobalVariableValue",
                        "arguments":[{
                            "exprType":"globalVariableLiteral",
                            "variableName":"Login"}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"2",
                        "stos":[]}},
                    "actions":[{
                        "action":"fadeWidget",
                        "description":"显示 退出登录按钮",
                        "objectsToFades":[{
                            "objectPath":["117de39a6b174043ab639e4de8e4f32b"],
                            "fadeInfo":{
                              "fadeType":"show",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f8ae19a9cdd744518715d4848eb273d4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "location":{
                "x":702,
                "y":37},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7bd1fee1ab164844b5cb5814b7d21eb0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "location":{
                    "x":702,
                    "y":37},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"117de39a6b174043ab639e4de8e4f32b",
            "label":"退出登录按钮",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":false,
            "style":{
              "location":{
                "x":1095,
                "y":74},
              "size":{
                "width":70,
                "height":70},
              "visible":false},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"setFunction",
                        "description":"设置 值于 Login = &quot;1&quot;",
                        "expr":{
                          "exprType":"block",
                          "subExprs":[{
                              "exprType":"fcall",
                              "functionName":"SetGlobalVariableValue",
                              "arguments":[{
                                  "exprType":"globalVariableLiteral",
                                  "variableName":"Login"},
{
                                  "exprType":"stringLiteral",
                                  "value":"1",
                                  "stos":[]}]}]}},
{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"},
{
                        "action":"fadeWidget",
                        "description":"隐藏 This",
                        "objectsToFades":[{
                            "objectPath":["117de39a6b174043ab639e4de8e4f32b"],
                            "fadeInfo":{
                              "fadeType":"hide",
                              "options":{
                                "showType":"none"}}}]}]}]}},
            "tabbable":true,
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"094f13922d86494393e52aeae360066d",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"34968a8b32ae4822b5b6e14742aa4f37",
                    "label":"",
                    "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                    "type":"table",
                    "styleType":"table",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontWeight":"400",
                      "fontStyle":"normal",
                      "size":{
                        "width":70,
                        "height":40}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"67d700fd08904918b4738f1d0e6d4d71",
                        "label":"",
                        "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                        "type":"tableCell",
                        "styleType":"tableCell",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontWeight":"400",
                          "fontStyle":"normal",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "size":{
                            "width":70,
                            "height":40}},
                        "adaptiveStyles":{
},
                        "objects":[{
                            "id":"5465cbdd1fca49f3927ee512d77e43bc",
                            "label":"",
                            "isContained":true,
                            "parentDynamicPanel":"117de39a6b174043ab639e4de8e4f32b",
                            "type":"richTextPanel",
                            "styleType":"paragraph",
                            "visible":true,
                            "style":{
                              "fontName":"'微软雅黑 Regular', '微软雅黑'",
                              "fontWeight":"400",
                              "fontStyle":"normal",
                              "horizontalAlignment":"center",
                              "verticalAlignment":"middle",
                              "size":{
                                "width":70,
                                "height":40}},
                            "adaptiveStyles":{
}}],
                        "images":{
                          "normal~":"images/首页（新）/u78.png"}}]}],
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "image":null,
                  "imageHorizontalAlignment":"near",
                  "imageVerticalAlignment":"near",
                  "imageRepeat":"auto"},
                "adaptiveStyles":{
}}]}]}},
    "36acf1ef35a04a2486fa269800e377cb":{
      "packageId":"36acf1ef35a04a2486fa269800e377cb",
      "type":"Axure:Master",
      "name":"foot",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"45784cc34d2243668a240874e0be3625",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontWeight":"400",
              "fontStyle":"normal",
              "fill":{
                "fillType":"solid",
                "color":0xFF666666},
              "location":{
                "x":-61,
                "y":244},
              "size":{
                "width":1766,
                "height":200}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cb36fade8eda427092d916bd825567ca",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF666666},
                  "location":{
                    "x":-61,
                    "y":244},
                  "size":{
                    "width":1766,
                    "height":200}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/登录/u49.png"}},
{
            "id":"eb14d540577d4325aef6c8a52dcc111c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":444,
                "y":280},
              "size":{
                "width":394,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f19d5fd6f5d4454f95b2b7e119099e88",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":444,
                    "y":280},
                  "size":{
                    "width":394,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f9cd1eb4f29b428eb0c2df9bdb23fcf0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":545,
                "y":324},
              "size":{
                "width":289,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59bf2f5a09994af893cf0d2cefb2564a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":545,
                    "y":324},
                  "size":{
                    "width":289,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8187b68a46584b3e8e8633bc4d28a79a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":377,
                "y":384},
              "size":{
                "width":623,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2582237d217c46bf878e7852b877a1a6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":377,
                    "y":384},
                  "size":{
                    "width":623,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"869bf3c4952e4e4fa146f90d1b21e694",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "fontWeight":"400",
              "fontStyle":"normal",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":870,
                "y":280},
              "size":{
                "width":73,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9483d61963448a2896b12b59d1e4e5a",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "fontWeight":"400",
                  "fontStyle":"normal",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":870,
                    "y":280},
                  "size":{
                    "width":73,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 规则协议列表",
                        "target":{
                          "targetType":"page",
                          "url":"规则协议列表.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "c93526a45f57476898b54215fe99e4de":{
      "scriptId":"u0"},
    "2c9a8d379f8a45eaa830fb804fee886e":{
      "scriptId":"u1"},
    "e009010d79354c748a6722b498ebb3dc":{
      "scriptId":"u2",
      "1821ab6eea004513b061fb3aaa34807b":{
        "scriptId":"u3"},
      "3bfc5bb18d4044fcafe4322f50ed83d9":{
        "scriptId":"u4"},
      "c4e8ce9ccacd42b79e2d44b619262fc6":{
        "scriptId":"u5"},
      "ff364c73fa734d488d3f95012d9de738":{
        "scriptId":"u6"},
      "5b9fb65a74544ef1bb7174c29a60cf33":{
        "scriptId":"u7"},
      "89b7bc5ad7e448f6a39423d68a75b281":{
        "scriptId":"u8"},
      "5493edf72eac416e8d507c5bf9a3a54a":{
        "scriptId":"u9"},
      "e04a737dd06a42dbb80844f1e2ce75d3":{
        "scriptId":"u10"},
      "91d413a8249e4dbe88f0bac22dd6425f":{
        "scriptId":"u11"},
      "d09956ae518b4d95892d6b5f7d466693":{
        "scriptId":"u12"},
      "7020ea293ef94676b8b39c2cc702250a":{
        "scriptId":"u13"},
      "24629670b3e34032a452acd4dfe4ecb1":{
        "scriptId":"u14"},
      "95d40ea0e0d04411a1f93c924484046c":{
        "scriptId":"u15"},
      "9d067be757bc4d9eb55a68f2214e3ab6":{
        "scriptId":"u16"},
      "cce804af75f845aaaef9cf4ea298aa28":{
        "scriptId":"u17"},
      "6e77319d89004f1a88255ae1719600a0":{
        "scriptId":"u18"},
      "f8ae19a9cdd744518715d4848eb273d4":{
        "scriptId":"u19"},
      "7bd1fee1ab164844b5cb5814b7d21eb0":{
        "scriptId":"u20"},
      "117de39a6b174043ab639e4de8e4f32b":{
        "scriptId":"u21"},
      "34968a8b32ae4822b5b6e14742aa4f37":{
        "scriptId":"u22"},
      "67d700fd08904918b4738f1d0e6d4d71":{
        "scriptId":"u23"},
      "5465cbdd1fca49f3927ee512d77e43bc":{
        "scriptId":"u24"}},
    "803f05126d234deca2008e0a0539c43b":{
      "scriptId":"u25"},
    "89b6f2dddf804d888b8770e71a376268":{
      "scriptId":"u26"},
    "c44cea64f75b4ce48842ec7b79699051":{
      "scriptId":"u27"},
    "2bff3bf2d9c64114bd4cab43486a011f":{
      "scriptId":"u28"},
    "f06ab9bb9fda42a285309ab5fc5303d4":{
      "scriptId":"u29"},
    "87a8aa52b145491e8cc7faeea7e27413":{
      "scriptId":"u30"},
    "a027649fe63344f896e49179714b81fc":{
      "scriptId":"u31"},
    "e00bf03341374f5fbfb6b90c5d90ffaf":{
      "scriptId":"u32"},
    "3c0f28b7ef4340968edb12d108a05a9b":{
      "scriptId":"u33"},
    "fb6cc0be4484428eb80a58e887879d05":{
      "scriptId":"u34"},
    "975efaa1aba8443299d257d08109b66f":{
      "scriptId":"u35"},
    "bfb058ed614b4d3c9e8a9496eaff64ab":{
      "scriptId":"u36"},
    "a19ddf4cff554a1baace60f8b84bba06":{
      "scriptId":"u37"},
    "a4ee080eab3244608336578deae30d2f":{
      "scriptId":"u38"},
    "901437d62fde4b68a8caffdcdf65b91a":{
      "scriptId":"u39"},
    "ea2b1f479d57442a9c8ef762bffac253":{
      "scriptId":"u40"},
    "e46346f7c87c4500b5cd9a9e9f808bb0":{
      "scriptId":"u41"},
    "650aaf5c5074481fa513ab861872b05d":{
      "scriptId":"u42"},
    "38b9a30fdf9146cca21445c3a03024cd":{
      "scriptId":"u43"},
    "85bcf15880de441a9cde0b06a707e155":{
      "scriptId":"u44"},
    "9ab17c14e8b94dc3802e16e67c669e37":{
      "scriptId":"u45"},
    "e95d1336a1ce417e9066c7b476769974":{
      "scriptId":"u46"},
    "cf340e29b70744d591849aca639fb3ad":{
      "scriptId":"u47"},
    "9f97a14d5d9f4f5fae148189a3589faa":{
      "scriptId":"u48"},
    "f114661b59014d8c917ec3a4627d6af9":{
      "scriptId":"u49"},
    "fdf60de0d076470d9d644b650aae72e4":{
      "scriptId":"u50"},
    "be82d903542f4dd8b2c90a00bd9f95c4":{
      "scriptId":"u51"},
    "83475e486b484fa58c37e41f4bcabaf3":{
      "scriptId":"u52",
      "45784cc34d2243668a240874e0be3625":{
        "scriptId":"u53"},
      "cb36fade8eda427092d916bd825567ca":{
        "scriptId":"u54"},
      "eb14d540577d4325aef6c8a52dcc111c":{
        "scriptId":"u55"},
      "f19d5fd6f5d4454f95b2b7e119099e88":{
        "scriptId":"u56"},
      "f9cd1eb4f29b428eb0c2df9bdb23fcf0":{
        "scriptId":"u57"},
      "59bf2f5a09994af893cf0d2cefb2564a":{
        "scriptId":"u58"},
      "8187b68a46584b3e8e8633bc4d28a79a":{
        "scriptId":"u59"},
      "2582237d217c46bf878e7852b877a1a6":{
        "scriptId":"u60"},
      "869bf3c4952e4e4fa146f90d1b21e694":{
        "scriptId":"u61"},
      "b9483d61963448a2896b12b59d1e4e5a":{
        "scriptId":"u62"}}}});